package api

import (
	"encoding/json"

	"github.com/alttab8520/qqfarm-sdk/internal/version"
)

func openAPI() orderedObject {
	return orderedObject{
		keys: []string{"openapi", "info", "servers", "tags", "paths", "components"},
		vals: map[string]any{
			"openapi": "3.0.3",
			"info": map[string]any{
				"title":   "qqfarm-sdk",
				"version": version.Version,
				"description": "非官方 QQ 农场协议 HTTP SDK。按模块和活动玩法分类。\n\n" +
					"接口是 `POST /模块/动作`，只有 `GET /YYB/Image` 例外。HTTP 状态码一般是 200，看 body：\n\n" +
					"| code | 含义 |\n|---|---|\n| 0 | 成功，看 `data` |\n| 400 | 入参不对 |\n| 401 | 未登录 |\n| 502 | 网关/RPC 失败，`msg` 是原因 |\n\n" +
					"`data` 因接口而异，下面每个接口都能展开请求体和回包字段。活动档期看对应分类的说明。",
			},
			"servers": []any{map[string]any{"url": "http://127.0.0.1:8765"}},
			"tags":    openAPITags(),
			"paths":   orderedPaths(openAPIPaths()),
			"components": map[string]any{
				"schemas": openAPISchemas(),
			},
		},
	}
}

func openAPIJSON() []byte {
	raw, err := json.MarshalIndent(openAPI(), "", "  ")
	if err != nil {
		return []byte(`{"openapi":"3.0.3","info":{"title":"qqfarm-sdk"}}`)
	}
	return raw
}

func s(typ, desc string) map[string]any {
	return map[string]any{"type": typ, "description": desc}
}

func si(desc string) map[string]any { return s("integer", desc) }
func ss(desc string) map[string]any { return s("string", desc) }
func sb(desc string) map[string]any { return s("boolean", desc) }

func ref(name string) map[string]any {
	return map[string]any{"$ref": "#/components/schemas/" + name}
}

func arr(item map[string]any, desc string) map[string]any {
	return map[string]any{"type": "array", "description": desc, "items": item}
}

func obj(desc string, props map[string]any) map[string]any {
	return map[string]any{"type": "object", "description": desc, "properties": props}
}

func wrap(data map[string]any) map[string]any {
	return obj("统一回包", map[string]any{
		"code": si("0 成功；400 入参；401 未登录；502 网关失败"),
		"msg":  ss("说明。失败时是原因"),
		"data": data,
	})
}

func docOp(tag, summary, desc, req string, data map[string]any) map[string]any {
	op := map[string]any{
		"tags":        []string{tag},
		"summary":     summary,
		"description": desc,
		"responses": map[string]any{
			"200": map[string]any{
				"description": "看 body.code，不是 HTTP 状态码",
				"content": map[string]any{
					"application/json": map[string]any{"schema": wrap(data)},
				},
			},
		},
	}
	if req != "" {
		op["requestBody"] = map[string]any{
			"required": false,
			"content": map[string]any{
				"application/json": map[string]any{"schema": ref(req)},
			},
		}
	}
	return map[string]any{"post": op}
}

func openAPISchemas() map[string]any {
	return map[string]any{
		"LoginIn": obj("登录", map[string]any{
			"code":    ss("登录票据，必填。可从 YYB/Code 拿"),
			"open_id": ss("平台 openid，能带上就带"),
		}),
		"YYBAccount": obj("应用宝账号", map[string]any{
			"id":         si("库内 ID"),
			"openid":     ss("微信 openid"),
			"uin":        si("微信 uin"),
			"nickname":   ss("昵称。Confirm / Profile 从应用宝资料拉"),
			"avatar":     ss("头像 URL。Confirm / Profile 从应用宝资料拉"),
			"status":     ss("alive / expired / unknown"),
			"updated_at": si("更新时间"),
		}),
		"YYBQROut": obj("扫码会话", map[string]any{
			"session_id": ss("会话 ID，后面 Poll / Confirm 带上"),
			"status":     ss("pending"),
			"image":      ss("data:image/jpeg;base64,..."),
		}),
		"YYBSessionIn": obj("扫码会话", map[string]any{
			"session_id": ss("来自 YYB/QR"),
		}),
		"YYBPollOut": obj("扫码状态", map[string]any{
			"status":  ss("pending / scanned / authorized / cancelled / expired / confirmed / unknown"),
			"errcode": si("微信 errcode"),
			"msg":     ss("说明"),
		}),
		"YYBRefIn": obj("应用宝账号", map[string]any{
			"ref":    ss("账号 id / openid / uin。空则用第一条"),
			"app_id": ss("小程序 appid。不填用农场默认"),
		}),
		"YYBCodeOut": obj("小程序 code", map[string]any{
			"code":   ss("一次性登录票据"),
			"openid": ss("微信 openid"),
		}),
		"YYBRefreshOut": obj("刷新登录态", map[string]any{
			"id":     si("账号 ID"),
			"openid": ss("openid"),
			"status": ss("alive 才能取 code"),
		}),
		"YYBDeleteOut": obj("删本地扫码账号", map[string]any{
			"deleted": si("删掉的库内 ID"),
			"openid":  ss("openid"),
		}),
		"YYBWXDataIn": obj("微信云函数代理", map[string]any{
			"ref":     ss("账号 id / openid / uin。空则用第一条"),
			"app_id":  ss("小程序 appid。不填用农场默认"),
			"payload": map[string]any{"type": "object", "description": "operateWxData 请求体，通常带 api_name", "additionalProperties": true},
		}),
		"YYBRawOut": obj("应用宝原始回包", map[string]any{
			"openid": ss("微信 openid"),
			"result": map[string]any{"type": "object", "description": "协议层原样回包", "additionalProperties": true},
		}),
		"ResEntry": obj("配表一行", map[string]any{
			"id":       si("资源 ID"),
			"table":    ss("来自哪张官方配表，如 ItemInfo / Plant / Goods"),
			"name":     ss("名字"),
			"type":     ss("配表自己的类型。有的是数字有的是中文，统一按字符串给"),
			"desc":     ss("描述"),
			"icon_url": ss("官方 CDN 上的 PNG，直接能下。种子是种子袋图，果实是成熟立绘。没有图就不给这个字段"),
			"extra":    map[string]any{"type": "object", "description": "该行剩下的字段，如 seed_id / fruit_id / land_level_need。也含原始资源引用 icon_res / asset_name，那是游戏内路径", "additionalProperties": true},
		}),
		"ResLookupIn": obj("按 ID 查", map[string]any{
			"ids":   arr(si(""), "要查的 ID。同一个 ID 可能在多张表里都有"),
			"table": ss("只看这张表。不填则全表查"),
		}),
		"ResListIn": obj("列配表", map[string]any{
			"table":   ss("表名，如 ItemInfo。不填则跨表"),
			"type":    ss("按配表自己的 type 过滤，如种子是 5"),
			"keyword": ss("按名字或描述模糊匹配"),
			"offset":  si("跳过几条"),
			"limit":   si("最多回几条，默认 200"),
		}),
		"ResListOut": obj("配表查询结果", map[string]any{
			"entries": arr(ref("ResEntry"), "命中的行"),
			"total":   si("命中总数，不受 limit 影响"),
			"source":  ss("bundled 内置 / cache 本地缓存 / cdn 刚刷新过"),
			"version": ss("生成这份表时的游戏包版本"),
		}),
		"ResTablesOut": obj("有哪些配表", map[string]any{
			"tables":  arr(obj("一张表", map[string]any{"name": ss("表名"), "count": si("行数")}), "配表清单"),
			"total":   si("总行数"),
			"source":  ss("bundled / cache / cdn"),
			"version": ss("游戏包版本"),
		}),
		"ResRefreshIn": obj("从官方 CDN 刷新", map[string]any{
			"bundle_vers": map[string]string{"type": "object", "description": "覆盖 mainscene / delayRes 的资源哈希。游戏更新后 SDK 内置的会过期，这时自己填"},
		}),
		"ResRefreshOut": obj("刷新结果", map[string]any{
			"tables":  si("拉到几张表"),
			"entries": si("拉到几行"),
			"source":  ss("恒为 cdn"),
			"version": ss("游戏包版本"),
			"cache":   ss("写到了哪个文件"),
		}),
		"User": obj("用户资料", map[string]any{
			"gid":         si("游戏内用户 ID"),
			"name":        ss("昵称"),
			"level":       si("等级"),
			"exp":         si("经验"),
			"gold":        si("金币"),
			"open_id":     ss("平台 openid"),
			"avatar_url":  ss("头像 URL"),
			"remark":      ss("备注"),
			"signature":   ss("签名"),
			"gender":      si("性别"),
			"authorized":  si("实名状态"),
			"last_online": si("最近在线"),
		}),
		"Status": obj("登录和长会话状态", map[string]any{
			"logged_in":  sb("是否已登录"),
			"user":       ref("User"),
			"ace":        ref("ACE"),
			"host_gid":   si("当前所在农场主人。0 或空是自己家"),
			"heartbeats": si("已发网关心跳次数。登录后每 25 秒自动发"),
			"server_ms":  si("最近一次心跳的服务端时间，毫秒"),
			"weather":    ref("Weather"),
		}),
		"Relation": obj("关系", map[string]any{
			"friend":    sb("是好友"),
			"community": sb("同社区"),
			"stranger":  sb("陌生人"),
		}),
		"ACE": obj("ACE 长会话计数。登录后自动跑，没有 /Ace 接口", map[string]any{
			"uploads":        si("Ace.AntiData 成功次数。包体是运行时吐的字节，调用方组不出来"),
			"status_reports": si("状态上报次数。大约 150 秒后才有"),
			"failures":       si("连续失败次数"),
			"last_error":     ss("最近一次错误"),
		}),
		"HeartbeatOut": obj("心跳回包", map[string]any{
			"server_ms": si("服务端时间，毫秒"),
			"host_gid":  si("这次心跳带的农场主人"),
		}),
		"RefreshIn": obj("刷新/心跳", map[string]any{
			"host_gid": si("目标农场主人。不填或 0 是自己"),
		}),
		"EnterIn": obj("按 gid", map[string]any{
			"gid": si("目标用户 gid"),
		}),
		"OpenIDsIn": obj("按 openid 列表", map[string]any{
			"open_ids": arr(ss(""), "openid 列表"),
		}),
		"ArkIn": obj("ARK 点击上报", map[string]any{
			"gid":      si("对方 gid"),
			"open_id":  ss("对方 openid"),
			"scene":    ss("场景。不填默认渠道 1256"),
			"share_id": si("分享 ID"),
			"key":      ss("分享 key"),
		}),
		"Land": obj("地块", map[string]any{
			"id":               si("地块编号"),
			"unlocked":         sb("是否已开垦"),
			"level":            si("地块等级"),
			"max_level":        si("地块最大等级"),
			"could_unlock":     sb("能不能解锁"),
			"could_upgrade":    sb("能不能升级"),
			"shared":           sb("是否已分享解锁"),
			"can_share":        sb("能不能分享解锁"),
			"master_land_id":   si("主地块。附属地非 0"),
			"slave_land_ids":   arr(si(""), "附属地块"),
			"land_size":        si("地块大小"),
			"plant_id":         si("作物 ID"),
			"plant_name":       ss("作物名"),
			"fruit_id":         si("果实 ID"),
			"fruit_num":        si("本季总产量"),
			"dry_num":          si("干旱格数。>0 要浇水"),
			"has_weed":         sb("有草"),
			"has_insect":       sb("有虫"),
			"stealable":        sb("能不能偷"),
			"left_fruit":       si("剩余果实"),
			"grow_sec":         si("总生长秒数"),
			"season":           si("季数"),
			"phase":            si("生长阶段。0种子 6成熟 7枯萎"),
			"stole_num":        si("被偷次数"),
			"stealers":         arr(si(""), "偷过的人 gid"),
			"mutant":           sb("是否变异"),
			"mutant_ids":       arr(si(""), "变异配置 ID"),
			"lands_level":      si("地块组等级"),
			"fert_left":        si("剩余有机肥次数"),
			"intimacy":         si("可偷所需亲密度"),
			"plant_exp":        si("本季经验"),
			"last_fruit":       si("上一季果实"),
			"last_fruit_num":   si("上一季产量"),
			"source_fruit":     si("未变异果实"),
			"source_fruit_num": si("未变异产量"),
			"source_price_id":  si("卖价货币"),
			"source_price":     si("单果卖价"),
			"mutant_price_id":  si("变异卖价货币"),
			"mutant_price":     si("变异单果卖价"),
			"unlock":           ref("LandNeed"),
			"upgrade":          ref("LandNeed"),
			"buff":             ref("LandBuff"),
			"social_items":     arr(ref("CropItem"), "地块上的社交道具"),
		}),
		"LandNeed": obj("解锁/升级条件", map[string]any{
			"land_id": si("前置地块。解锁用"),
			"lands":   si("已解锁地块数。升级用"),
			"level":   si("所需等级"),
			"gold":    si("所需金币"),
			"items":   arr(ref("Item"), "所需物品"),
		}),
		"LandBuff": obj("地块加成", map[string]any{
			"yield":  si("产量"),
			"time":   si("生长时间缩减"),
			"exp":    si("经验"),
			"mutant": si("变异率"),
			"pass":   si("战令经验"),
		}),
		"CropItem": obj("作物上的社交道具", map[string]any{
			"item_id":  si("道具"),
			"count":    si("数量"),
			"type":     si("类型"),
			"owner_id": si("放置者。作物级事件才有"),
			"put_time": si("开始时间"),
			"end":      si("结束时间"),
			"land_id":  si("地块。作物级事件才有"),
		}),
		"Item": obj("物品。id 是类型，不是背包格子", map[string]any{
			"id":    si("物品类型 ID。1001 金币，1002 点券"),
			"count": si("数量"),
		}),
		"RefreshLandsIn": obj("增量刷新", map[string]any{
			"land_ids": arr(si(""), "地块。空则不发包"),
			"host_gid": si("目标农场。不填是自己"),
		}),
		"CleanSocialIn": obj("清地块社交道具", map[string]any{
			"land_ids": arr(si(""), "地块。必填。有乌云的地从 Refresh.social_items 取"),
			"item_ids": arr(si(""), "要清的道具。乌云 5006，黄金虫等。可不填则这块地上能清的都清。青蛙不走这里"),
		}),
		"HarvestIn": obj("收获/偷菜", map[string]any{
			"land_ids": arr(si(""), "地块"),
			"host_gid": si("偷菜必须填好友 gid"),
			"is_all":   sb("是否一键全部"),
		}),
		"HarvestOut": obj("收获/偷菜回包", map[string]any{
			"items":    arr(ref("Item"), "收到的"),
			"lost":     arr(ref("Item"), "背包满等原因丢掉的"),
			"extra":    arr(ref("Item"), "额外奖励"),
			"lands":    arr(ref("Land"), "更新后的地块"),
			"limits":   arr(ref("OpLimit"), "今日次数"),
			"drops":    arr(ref("LandDrop"), "地块掉落"),
			"warnings": arr(ref("HarvestWarn"), "警告。背包满一类"),
			"buffs":    arr(ref("Buff"), "这次触发的加成"),
		}),
		"HarvestWarn": obj("收获警告", map[string]any{
			"land_id": si("地块"),
			"text":    ss("文案"),
		}),
		"OpLimit": obj("操作次数", map[string]any{
			"id":           si("操作类型"),
			"used":         si("今日已用"),
			"limit":        si("每日上限"),
			"share_id":     si("分享加次数配置"),
			"exp_used":     si("今日已获经验次数"),
			"exp_limit":    si("每日经验次数上限"),
			"exp_share_id": si("分享加经验次数配置"),
		}),
		"LandDrop": obj("地块操作掉落", map[string]any{
			"land_id": si("地块"),
			"rewards": arr(ref("Item"), "获得"),
			"costs":   arr(ref("Item"), "消耗"),
			"skills":  arr(si(""), "触发的技能"),
		}),
		"FarmSocial": obj("农场级使坏", map[string]any{
			"item_id":  si("道具。青蛙使坏瓶是 5005"),
			"owner_id": si("放置者"),
			"put_time": si("放置时间"),
		}),
		"LandSocial": obj("地块社交道具", map[string]any{
			"land_id": si("地块"),
			"items":   arr(ref("Item"), "道具"),
		}),
		"FarmReward": obj("农场级奖励", map[string]any{
			"source_item_id": si("来源道具"),
			"items":          arr(ref("Item"), "奖励"),
		}),
		"LandOpOut": obj("地对操作回包", map[string]any{
			"lands":   arr(ref("Land"), "更新后的地块"),
			"limits":  arr(ref("OpLimit"), "今日次数"),
			"drops":   arr(ref("LandDrop"), "地块掉落"),
			"costs":   arr(ref("Item"), "消耗。施肥是肥料"),
			"social":  arr(ref("LandSocial"), "地块上的社交道具"),
			"events":  arr(ref("FarmSocial"), "农场级使坏。全量刷新才有"),
			"rewards": arr(ref("FarmReward"), "清农场级使坏的奖励。务农才有"),
		}),
		"ItemOpOut": obj("背包使用/出售回包", map[string]any{
			"used":        arr(ref("Item"), "消耗/卖出的"),
			"items":       arr(ref("Item"), "获得的"),
			"compensated": arr(ref("Item"), "背包满补偿"),
		}),
		"FriendsOut": obj("好友列表", map[string]any{
			"friends":           arr(ref("Friend"), "好友"),
			"application_count": si("待处理申请数"),
			"blocked":           arr(ref("Blocked"), "我拉黑的"),
			"blocked_by":        arr(ref("Blocked"), "拉黑我的"),
		}),
		"PutSocialIn": obj("放使坏瓶", map[string]any{
			"land_ids": arr(si(""), "地块。乌云 5006 必填。青蛙 5005 不填"),
			"host_gid": si("目标农场"),
			"item_id":  si("道具。青蛙使坏瓶 5005，乌云使坏瓶 5006"),
		}),
		"InviteReportIn": obj("上报邀请", map[string]any{
			"open_id":   ss("被邀请人 openid"),
			"share_key": ss("分享 key"),
		}),
		"CanOperateOut": obj("预检结果", map[string]any{
			"ok":        sb("能不能做"),
			"steal_num": si("还能偷多少。operation_id=10004 时有效"),
		}),
		"ShopBuyItem": obj("活动商店一件货", map[string]any{
			"goods_id": si("商品 ID"),
			"count":    si("数量"),
		}),
		"ActivityBatchIn": obj("活动商店批量买", map[string]any{
			"id":    si("活动 ID"),
			"items": arr(ref("ShopBuyItem"), "要买的"),
		}),
		"RandGoods": obj("随机商店一件货", map[string]any{
			"id":        si("商品 ID"),
			"name":      ss("名字"),
			"desc":      ss("说明"),
			"items":     arr(ref("Item"), "卖的东西"),
			"cost":      arr(ref("Item"), "要花的"),
			"limit":     si("限购"),
			"bought":    si("已买"),
			"available": sb("现在能不能买"),
		}),
		"RandShop": obj("随机商店货架", map[string]any{
			"goods":           arr(ref("RandGoods"), "货架"),
			"next_refresh":    si("下次自动刷新时间"),
			"refresh_cost":    si("手动刷新花费数量"),
			"refresh_cost_id": si("手动刷新货币 ID"),
			"diamond_cost":    si("点券刷新价"),
			"daily_limit":     si("每日刷新上限"),
			"today_count":     si("今日已刷新"),
			"free_limit":      si("免费刷新上限"),
			"free_today":      si("今日已免费刷新"),
		}),
		"PlantIn": obj("种植", map[string]any{
			"seed_id":  si("种子物品 ID"),
			"land_ids": arr(si(""), "地块"),
		}),
		"RemoveIn": obj("铲地", map[string]any{
			"land_ids": arr(si(""), "地块"),
		}),
		"LandIDIn": obj("单块地", map[string]any{
			"land_id": si("地块编号"),
		}),
		"LandOpIn": obj("地对操作", map[string]any{
			"land_ids": arr(si(""), "地块"),
			"host_gid": si("目标农场。放虫放草必须填好友"),
			"item_ids": arr(si(""), "务农时顺手清农场级使坏。青蛙 5005。乌云不走这里"),
		}),
		"FertilizeIn": obj("施肥", map[string]any{
			"land_ids":      arr(si(""), "地块"),
			"fertilizer_id": si("肥料物品 ID"),
		}),
		"CanOperateIn": obj("预检", map[string]any{
			"host_gid":     si("好友 gid"),
			"operation_id": si("10001 务农 10004 偷菜 10005 放虫 10006 放草"),
		}),
		"Friend": obj("好友", map[string]any{
			"gid":           si("gid"),
			"name":          ss("昵称"),
			"level":         si("等级"),
			"open_id":       ss("openid"),
			"avatar_url":    ss("头像"),
			"remark":        ss("备注"),
			"gold":          si("金币"),
			"authorized":    si("实名状态"),
			"last_login":    si("最近登录"),
			"dry_num":       si("干旱地块数"),
			"weed_num":      si("有草地块数"),
			"insect_num":    si("有虫地块数"),
			"steal_num":     si("可偷地块数"),
			"new":           sb("新好友"),
			"follow":        sb("已关注"),
			"exp":           si("经验"),
			"banned":        sb("被封"),
			"host_type":     si("宿主类型"),
			"returner":      sb("回流"),
			"album_normal":  si("普通图鉴进度"),
			"album_premium": si("超变图鉴进度"),
			"pass_season":   si("战令赛季"),
			"pass_level":    si("战令等级"),
			"weather":       ref("Weather"),
		}),
		"HelpIn": obj("帮忙", map[string]any{
			"gid":      si("好友 gid"),
			"land_ids": arr(si(""), "要浇的地。可不填"),
		}),
		"Visit": obj("进别人家", map[string]any{
			"host":         ref("User"),
			"lands":        arr(ref("Land"), "地块"),
			"dog_id":       si("出战犬"),
			"dog_food_sec": si("狗粮剩余秒"),
			"apply_token":  ss("进门带出来的字段，不是申请接口"),
			"at_home":      sb("房主在家"),
			"tourist":      sb("游客身份"),
			"server_ms":    si("服务器时间毫秒"),
			"friend":       sb("是不是好友"),
			"community":    sb("同社区"),
			"limits":       arr(ref("OpLimit"), "操作次数"),
			"weather":      ref("Weather"),
		}),
		"Application": obj("好友申请", map[string]any{
			"gid":        si("申请人 gid"),
			"time":       si("申请时间"),
			"open_id":    ss("openid"),
			"name":       ss("昵称"),
			"avatar_url": ss("头像"),
		}),
		"ApplicationsOut": obj("申请列表", map[string]any{
			"applications": arr(ref("Application"), "申请"),
			"blocked":      sb("屏蔽了申请"),
		}),
		"AcceptOut": obj("同意申请", map[string]any{
			"friends": arr(ref("Friend"), "新好友"),
			"success": si("成功数"),
			"failed":  si("失败数"),
			"full":    si("对方好友已满数"),
		}),
		"RejectOut": obj("拒绝申请", map[string]any{
			"count": si("拒绝成功数"),
		}),
		"TagsIn": obj("好友标签", map[string]any{
			"gid":    si("好友 gid"),
			"new":    sb("标成新好友"),
			"follow": sb("关注"),
		}),
		"GIDsIn": obj("gid 列表", map[string]any{
			"gids": arr(si(""), "gid 列表"),
		}),
		"Blocked": obj("黑名单项", map[string]any{
			"gid":        si("gid"),
			"name":       ss("昵称"),
			"open_id":    ss("openid"),
			"avatar_url": ss("头像"),
			"level":      si("等级"),
			"time":       si("拉黑时间"),
		}),
		"ShareInviteInfo": obj("邀请配置", map[string]any{
			"id":           si("分享配置 ID"),
			"share_key":    ss("分享 key"),
			"share_url":    ss("分享链接"),
			"invite_count": si("已邀请人数"),
			"reward_count": si("已领奖励数"),
			"can_claim":    sb("能不能领"),
		}),
		"ShareInviteOut": obj("邀请进度", map[string]any{
			"infos": arr(ref("ShareInviteInfo"), "各分享配置"),
		}),
		"ShareAwardOut": obj("领邀请奖", map[string]any{
			"info":        ref("ShareInviteInfo"),
			"awards":      arr(ref("Item"), "奖励"),
			"compensated": arr(ref("Item"), "补偿"),
			"awarded":     sb("是否已领取"),
		}),
		"IDIn": obj("单个 ID", map[string]any{
			"id": si("ID。活动/商品/邮件以外的数字 ID"),
		}),
		"BagItem": obj("背包格子", map[string]any{
			"id":         si("物品类型"),
			"count":      si("数量"),
			"uid":        si("格子 UID。使用/出售/酿酒要带这个，不是 id"),
			"sell_id":    si("卖出价货币。f4 才有"),
			"sell_price": si("单价。ItemShow.f1 或 f4.count"),
			"expire":     si("过期时间"),
			"new":        sb("新获得"),
			"locked":     sb("已锁定"),
			"mutants":    arr(si(""), "变异类型"),
		}),
		"BagOut": obj("背包", map[string]any{
			"items": arr(ref("BagItem"), "格子"),
			"max":   si("格子上限"),
			"used":  si("已占用"),
		}),
		"SellIn": obj("出售", map[string]any{
			"items": arr(ref("BagItem"), "要卖的格子。带 uid"),
		}),
		"UseIn": obj("使用一件", map[string]any{
			"id":       si("物品类型"),
			"count":    si("数量"),
			"uid":      si("格子 UID"),
			"host_gid": si("对别人用时填目标农场。使坏瓶请走 Farm/PutSocial"),
			"land_ids": arr(si(""), "对别人用地块道具时填"),
		}),
		"BatchUseIn": obj("批量使用", map[string]any{
			"items": arr(ref("UseIn"), "多件"),
		}),
		"UIDsIn": obj("格子列表", map[string]any{
			"uids": arr(si(""), "背包格子 UID"),
		}),
		"LockFail": obj("锁定失败", map[string]any{
			"uid":    si("格子"),
			"code":   si("错误码"),
			"reason": ss("原因"),
		}),
		"LockOut": obj("锁定结果", map[string]any{
			"newly":    arr(si(""), "刚锁上的"),
			"already":  arr(si(""), "本来就锁着的"),
			"failures": arr(ref("LockFail"), "失败的"),
		}),
		"Shop": obj("商店", map[string]any{
			"id":   si("商店 ID。2 是种子店"),
			"name": ss("名字"),
			"type": si("类型"),
		}),
		"ShopIn": obj("查货架", map[string]any{
			"shop_id": si("商店。不填当 2 种子店"),
		}),
		"ShopCond": obj("货架条件", map[string]any{
			"type":  si("条件类型。2 是等级"),
			"param": si("参数。等级阈值等"),
		}),
		"Goods": obj("货架商品", map[string]any{
			"id":         si("货架商品 ID，购买用这个"),
			"bought":     si("已买次数"),
			"price":      si("单价"),
			"limit":      si("限购"),
			"unlocked":   sb("是否解锁"),
			"item_id":    si("买到的物品类型"),
			"item_count": si("一份给多少"),
			"conds":      arr(ref("ShopCond"), "解锁/购买条件"),
			"countdown":  sb("显示倒计时"),
			"end_time":   si("结束时间"),
		}),
		"BuyIn": obj("购买", map[string]any{
			"goods_id": si("货架商品 ID"),
			"num":      si("份数"),
			"price":    si("单价，用货架上的"),
		}),
		"BuyOut": obj("购买结果", map[string]any{
			"items":     arr(ref("Item"), "得到的"),
			"cost":      arr(ref("Item"), "花掉的。商店才有"),
			"goods":     ref("Goods"),
			"success":   sb("商城购买是否成功"),
			"first_buy": sb("是不是第一次买"),
			"bought":    si("限购已买"),
			"limit":     si("限购上限"),
		}),
		"AutoBuyIn": obj("按物品买", map[string]any{
			"item_id": si("要买的物品类型"),
			"num":     si("份数"),
			"shop_id": si("商店。不填当种子店"),
		}),
		"Weather": obj("天气", map[string]any{
			"type":           si("天气类型"),
			"source":         si("来源"),
			"begin":          si("开始时间"),
			"end":            si("结束时间"),
			"active":         sb("当前是否生效"),
			"afterglow":      si("余晖"),
			"afterglow_type": si("余晖类型"),
			"can_collect":    sb("雨落成诗能不能采"),
			"block_reason":   si("不能采集的原因"),
			"name":           ss("名字"),
		}),
		"Task": obj("任务", map[string]any{
			"id":       si("任务 ID"),
			"progress": si("当前进度"),
			"total":    si("完成所需"),
			"claimed":  sb("已领奖"),
			"unlocked": sb("是否已解锁"),
			"type":     si("1 成长 2 每日"),
			"desc":     ss("描述"),
			"rewards":  arr(ref("Item"), "奖励"),
			"share":    si("分享倍数"),
			"group":    si("任务组"),
			"cond":     si("条件类型。每日任务也是活跃度点数"),
			"extra":    arr(ref("Item"), "活动额外奖励"),
		}),
		"TaskClaimOut": obj("领任务/宝箱", map[string]any{
			"items":       arr(ref("Item"), "拿到的"),
			"compensated": arr(ref("Item"), "背包满补偿"),
			"board":       ref("TaskBoard"),
		}),
		"ActiveBox": obj("活跃度宝箱", map[string]any{
			"id":        si("节点 ID，领取用 point_ids"),
			"need":      si("需要活跃度"),
			"status":    si("0 不够门槛 1 可领 2 已领"),
			"can_claim": sb("status=1"),
			"claimed":   sb("status=2"),
			"rewards":   arr(ref("Item"), "奖励"),
		}),
		"Active": obj("活跃度", map[string]any{
			"type":     si("1 每日 2 每周"),
			"progress": si("当前活跃度"),
			"boxes":    arr(ref("ActiveBox"), "宝箱"),
		}),
		"TaskBoard": obj("任务总览", map[string]any{
			"growth":  arr(ref("Task"), "成长任务"),
			"daily":   arr(ref("Task"), "每日任务"),
			"actives": arr(ref("Active"), "活跃度"),
		}),
		"ClaimIn": obj("领任务", map[string]any{
			"id":     si("一个任务 ID"),
			"ids":    arr(si(""), "多个则批量领"),
			"shared": sb("是否分享多倍。只对单个领取有效"),
		}),
		"DailyIn": obj("领活跃度宝箱", map[string]any{
			"point_ids": arr(si(""), "宝箱节点 ID"),
		}),
		"EmailClaimOut": obj("批量领邮件", map[string]any{
			"items":     arr(ref("Item"), "领到的"),
			"unclaimed": arr(ss(""), "没领成的邮件 ID"),
		}),
		"ShareClaimOut": obj("领分享奖", map[string]any{
			"success":    sb("是否成功"),
			"has_reward": sb("有没有奖"),
			"items":      arr(ref("Item"), "这次领到的"),
		}),
		"TaskReportIn": obj("上报进度", map[string]any{
			"id":       si("任务 ID"),
			"progress": si("进度增量"),
		}),
		"EmailBoxIn": obj("邮箱", map[string]any{
			"box": si("1 收件 2 常见另一个箱。不填当 1"),
			"id":  ss("批量领时可带单封邮件 ID。不填领该箱全部"),
		}),
		"EmailIn": obj("一封邮件", map[string]any{
			"box": si("邮箱。不填当 1"),
			"id":  ss("邮件 ID，字符串"),
		}),
		"EmailIDsIn": obj("多封邮件", map[string]any{
			"box": si("邮箱。不填当 1"),
			"ids": arr(ss(""), "邮件 ID"),
		}),
		"Email": obj("邮件摘要", map[string]any{
			"id":         ss("邮件 ID"),
			"type":       si("邮箱类型"),
			"title":      ss("标题"),
			"read":       sb("已读。列表这一位不是已领"),
			"has_reward": sb("有奖"),
			"subtitle":   ss("副标题"),
			"send_time":  si("发送时间"),
			"expire":     si("过期时间"),
			"tips":       ss("提示"),
		}),
		"Invitee": obj("邀新名单里的人", map[string]any{
			"gid":         si("gid"),
			"level":       si("等级"),
			"name":        ss("昵称"),
			"avatar_url":  ss("头像"),
			"register_at": si("注册时间"),
			"invited_at":  si("被邀请时间"),
		}),
		"VisitFriend": obj("来往统计里的人", map[string]any{
			"gid":            si("gid"),
			"name":           ss("昵称"),
			"avatar_url":     ss("头像"),
			"steal_count":    si("偷过几次"),
			"steal_item_num": si("偷走多少个"),
			"help_count":     si("帮过几次"),
			"mischief_count": si("捣乱几次"),
			"level":          si("等级"),
		}),
		"VisitSummary": obj("来往摘要", map[string]any{
			"steal_count":    si("总偷菜次数"),
			"help_count":     si("总帮忙次数"),
			"mischief_count": si("总捣乱次数"),
			"steal_item_num": si("总偷走数量"),
			"friends":        arr(ref("VisitFriend"), "按好友"),
		}),
		"BuyFail": obj("买失败的一项", map[string]any{
			"id":     si("商品 ID"),
			"reason": ss("原因"),
		}),
		"MysteryAutoOut": obj("神秘商人扫货结果", map[string]any{
			"items":  arr(ref("Item"), "买到的"),
			"failed": arr(ref("BuyFail"), "失败的。继续买，不会半路停"),
		}),
		"EmailDetail": obj("邮件正文", map[string]any{
			"id":        ss("邮件 ID"),
			"type":      si("邮箱"),
			"title":     ss("标题"),
			"content":   ss("正文"),
			"rewards":   arr(ref("Item"), "附件"),
			"send_time": si("发送时间"),
			"expire":    si("过期时间"),
			"read":      sb("已读"),
			"claimed":   sb("已领"),
			"reason":    ss("来源标识"),
			"tips":      ss("提示"),
		}),
		"GroupIn": obj("活动组", map[string]any{
			"id":       si("组 ID"),
			"group_id": si("和 id 二选一"),
		}),
		"ActivityGoods": obj("活动商店商品", map[string]any{
			"id":          si("商品 ID"),
			"name":        ss("名字"),
			"desc":        ss("说明"),
			"limit":       si("限购"),
			"bought":      si("已买"),
			"order":       si("排序"),
			"items":       arr(ref("Item"), "得到的"),
			"cost":        arr(ref("Item"), "花费"),
			"diamond":     si("点券价"),
			"background":  si("背景"),
			"restriction": si("限制类型"),
			"category":    ss("分类"),
		}),
		"TechNode": obj("科技树节点", map[string]any{
			"tree_id":  si("树 ID"),
			"id":       si("节点 ID"),
			"status":   si("0未知 1锁 2可建设/可领 3已完成 4已领"),
			"progress": si("进度"),
			"target":   si("目标"),
			"cost":     arr(ref("Item"), "消耗"),
			"rewards":  arr(ref("Item"), "奖励"),
		}),
		"LotteryInfo": obj("雨落成诗采集", map[string]any{
			"free_left":  si("免费剩余"),
			"free_limit": si("免费上限"),
			"paid_left":  si("付费剩余"),
			"paid_limit": si("付费上限"),
			"cost_id":    si("付费道具。天气采集瓶是 5001"),
			"cost_count": si("付费数量"),
			"diamond":    si("点券价"),
			"preview":    arr(si(""), "预览商品 ID"),
			"biz_type":   si("业务类型"),
		}),
		"BrewInfo": obj("酿酒", map[string]any{
			"value":       si("当前值"),
			"step":        si("当前步"),
			"steps":       si("总步数"),
			"multipliers": arr(si(""), "每步倍率"),
			"amounts":     arr(si(""), "每步增量"),
			"can_claim":   sb("能不能领"),
			"base":        si("基础倍率"),
			"allowed":     arr(si(""), "允许投入的物品类型"),
			"share":       si("分享倍率"),
		}),
		"RecallInfo": obj("故友重逢", map[string]any{
			"daily":          si("今日已邀"),
			"daily_limit":    si("每日上限"),
			"total":          si("累计召回"),
			"max":            si("召回上限"),
			"pending":        si("待领召回奖"),
			"pending_items":  arr(ref("Item"), "待领召回奖内容"),
			"returner":       sb("自己是回归玩家"),
			"login_at":       si("回归登录时间"),
			"buff_expire":    si("回归 buff 过期"),
			"buff_cd":        si("回归 buff CD"),
			"by_gid":         si("谁召回的自己"),
			"return_pending": si("待领回归礼"),
			"return_items":   arr(ref("Item"), "待领回归礼内容"),
		}),
		"InviteTask": obj("邀新档", map[string]any{
			"stage":        si("档位"),
			"desc":         ss("条件"),
			"target":       si("目标"),
			"current":      si("当前"),
			"completed":    sb("已完成"),
			"claimed":      sb("已领"),
			"growth_level": si("成长档等级"),
			"rewards":      arr(ref("Item"), "奖励"),
		}),
		"InviteInfo": obj("邀新", map[string]any{
			"invitee":      sb("自己是新人"),
			"invite_count": si("已邀请"),
			"growth_count": si("成长进度"),
			"limit":        si("上限"),
			"expire":       si("新人过期"),
			"inviter":      ref("Invitee"),
			"invite":       arr(ref("InviteTask"), "邀请档"),
			"growth":       arr(ref("InviteTask"), "成长档"),
			"newcomer":     arr(ref("InviteTask"), "新人档"),
		}),
		"GiftOffer": obj("可送的礼", map[string]any{
			"cost":    arr(ref("Item"), "花费"),
			"receive": arr(ref("Item"), "对方收到的"),
			"type":    si("类型"),
			"content": si("寄语池"),
		}),
		"GiftState": obj("送礼", map[string]any{
			"sent":          si("已送"),
			"send_limit":    si("送礼上限"),
			"receive_limit": si("收礼上限"),
			"gifts":         arr(ref("GiftOffer"), "礼清单"),
		}),
		"SigninReward": obj("签到档", map[string]any{
			"id":    si("档 ID，签到用 reward_id"),
			"desc":  ss("说明"),
			"items": arr(ref("Item"), "奖励"),
		}),
		"MegaReward": obj("观星礼录一天", map[string]any{
			"day":       si("第几天"),
			"unlocked":  sb("已解锁"),
			"claimed":   sb("已领"),
			"claimable": sb("可领"),
			"rewards":   arr(ref("Item"), "奖励"),
		}),
		"MegaSegment": obj("观星礼录章节", map[string]any{
			"level":    si("章节"),
			"unlocked": sb("已解锁"),
			"name":     ss("名字"),
			"art":      ss("资源"),
			"desc":     ss("说明"),
		}),
		"MegaEvent": obj("观星礼录", map[string]any{
			"day":      si("当前天"),
			"total":    si("赛季总天数"),
			"lookback": si("可补领天数"),
			"rewards":  arr(ref("MegaReward"), "每天奖励"),
			"events":   arr(ref("MegaSegment"), "章节"),
		}),
		"ProgressStep": obj("进度档", map[string]any{
			"step":    si("档"),
			"cost":    arr(ref("Item"), "消耗"),
			"rewards": arr(ref("Item"), "奖励"),
			"status":  si("1 未解锁 2 已领"),
		}),
		"ProgressReward": obj("进度奖", map[string]any{
			"preview":   arr(ref("Item"), "预览"),
			"steps":     arr(ref("ProgressStep"), "档位"),
			"unlocked":  si("已解锁到哪档"),
			"completed": sb("是否走完"),
		}),
		"ActivityOpOut": obj("活动操作回包", map[string]any{
			"items":      arr(ref("Item"), "得到的"),
			"costs":      arr(ref("Item"), "花掉的"),
			"days":       arr(si(""), "观星刚领的天数"),
			"steps":      arr(si(""), "进度刚解锁的档"),
			"completed":  sb("进度是否走完"),
			"gold":       si("酿酒金币"),
			"claim_type": si("酿酒领取类型"),
			"unlocked":   arr(si(""), "建设刚解锁的节点"),
			"activity":   ref("Activity"),
		}),
		"Activity": obj("活动", map[string]any{
			"id":               si("活动 ID，操作都带这个"),
			"group_id":         si("所属组"),
			"type":             si("活动类型"),
			"name":             ss("名字"),
			"desc":             ss("说明"),
			"start":            si("开始时间，Unix 秒。活动号不是开日，以这里为准"),
			"end":              si("结束时间，Unix 秒。本地配置没有结束日，以这里为准"),
			"client_id":        si("客户端展示 ID。采集 103、建设 104、故友 61、青酿日签 71、青酿 72、筑桥 111、香囊 112、寻宝 18"),
			"status":           si("1 进行中，2 已结束"),
			"splash_order":     si("开屏顺序"),
			"splashed":         sb("开屏已看"),
			"red_dot":          sb("红点"),
			"signin_claimed":   sb("今日签到已领"),
			"signin_reward_id": si("今日签到档 ID"),
			"signin":           arr(ref("SigninReward"), "签到档"),
			"shop":             arr(ref("ActivityGoods"), "活动商店。雨落成诗每日限购在这里"),
			"nodes":            arr(ref("TechNode"), "建设节点。雨落成诗领取走 TechSubmit"),
			"lottery":          ref("LotteryInfo"),
			"brew":             ref("BrewInfo"),
			"recall":           ref("RecallInfo"),
			"invite":           ref("InviteInfo"),
			"gift":             ref("GiftState"),
			"rand_shop":        ref("RandShop"),
			"mega":             ref("MegaEvent"),
			"progress":         ref("ProgressReward"),
			"draw":             ref("DrawInfo"),
			"cheer":            ref("CampCheer"),
			"charity":          ref("CharityFlower"),
			"drops":            arr(ref("DropPreview"), "活动里的随机掉落预览"),
			"hunt":             ref("Hunt"),
		}),
		"Hunt": obj("宠物寻宝", map[string]any{
			"treasures":                arr(ref("HuntTreasure"), "宝藏。status：1待开 2开启中 3已开 4已领"),
			"charm_daily_pool":         arr(ref("HuntCharm"), "当日护符池"),
			"charm_equipped":           arr(ref("HuntCharm"), "已装备护符"),
			"has_unread_plundered_log": sb("有未读被掠记录"),
		}),
		"HuntTreasure": obj("寻宝宝藏", map[string]any{
			"id":             ss("宝藏 ID"),
			"item_id":        si("物品"),
			"count":          si("当前价值"),
			"original_count": si("初始价值"),
			"create_at":      si("创建时间"),
			"status":         si("状态"),
			"start_at":       si("开启开始"),
			"end_at":         si("开启结束"),
		}),
		"HuntCharm": obj("寻宝护符", map[string]any{
			"id":              si("护符 ID，配置 101–105"),
			"total_use_count": si("可用次数，-1 不限"),
			"used_count":      si("已用次数"),
		}),
		"HuntEquipIn": obj("装备护符", map[string]any{
			"id":        si("活动 ID"),
			"charm_ids": arr(si(""), "护符 ID"),
		}),
		"HuntBattleIn": obj("寻宝开战", map[string]any{
			"id":           si("活动 ID，也可用 client_id"),
			"defender_gid": si("对方 gid"),
			"treasure_id":  ss("对方宝藏 ID"),
		}),
		"HuntLogOut": obj("寻宝日志", map[string]any{
			"logs":     arr(ref("HuntLogEntry"), "记录"),
			"activity": ref("Activity"),
		}),
		"HuntLogEntry": obj("寻宝被掠记录", map[string]any{
			"time":              si("时间"),
			"attacker_gid":      si("对方 gid"),
			"attacker_name":     ss("对方名"),
			"attacker_won":      sb("对方赢了"),
			"lost_items":        arr(ref("Item"), "自己掉的"),
			"attacker_use_item": arr(ref("Item"), "对方用的"),
			"injected_items":    arr(ref("Item"), "塞进来的"),
			"attack_avatar_url": ss("对方头像"),
		}),
		"ActivityGroup": obj("活动组", map[string]any{
			"id":         si("组 ID"),
			"name":       ss("名字"),
			"type":       si("类型"),
			"start":      si("组开始，Unix 秒"),
			"end":        si("组结束，Unix 秒。本地配置没有结束日，以这里为准"),
			"status":     si("1 进行中，2 已结束"),
			"activities": arr(ref("Activity"), "组内活动"),
		}),
		"ActivityOpIn": obj("活动操作", map[string]any{
			"id":        si("活动 ID"),
			"reward_id": si("签到档。可不填，从列表取"),
			"step":      si("进度档。一般 0"),
		}),
		"ActivityShopIn": obj("活动商店买", map[string]any{
			"id":       si("活动 ID"),
			"goods_id": si("商品 ID"),
			"count":    si("数量"),
		}),
		"TechIn": obj("雨落成诗建设/领取", map[string]any{
			"id":      si("带 nodes 的活动 ID，不是采集那条"),
			"node_id": si("节点 ID"),
		}),
		"DrawInfo": obj("活动抽奖", map[string]any{
			"today":       si("今日已抽"),
			"daily_limit": si("每日上限"),
			"cost":        arr(ref("Item"), "消耗"),
			"total":       si("累计抽数"),
		}),
		"DrawIn": obj("活动抽奖", map[string]any{
			"id":    si("活动 ID"),
			"count": si("次数。不填当 1"),
		}),
		"DrawRecord": obj("抽奖记录", map[string]any{
			"time":    si("时间"),
			"count":   si("次数"),
			"rewards": arr(ref("Item"), "奖品"),
		}),
		"DrawHistoryOut": obj("抽奖历史", map[string]any{
			"records":  arr(ref("DrawRecord"), "记录"),
			"activity": ref("Activity"),
		}),
		"LotteryRecord": obj("雨落成诗采集记录", map[string]any{
			"time":       si("时间"),
			"results":    arr(ref("LotteryHit"), "结果"),
			"cost_type":  si("消耗类型"),
			"cost_count": si("消耗数量"),
		}),
		"LotteryHistoryOut": obj("雨落成诗采集历史", map[string]any{
			"records":  arr(ref("LotteryRecord"), "记录"),
			"activity": ref("Activity"),
		}),
		"CampCheer": obj("阵营加油", map[string]any{
			"camp_id": si("阵营"),
			"cheer":   si("个人加油值"),
			"tiers":   arr(ref("CheerTier"), "档位"),
		}),
		"CheerTier": obj("加油档", map[string]any{
			"index":   si("档位"),
			"need":    si("所需"),
			"claimed": sb("已领"),
			"rewards": arr(ref("Item"), "奖励"),
		}),
		"CheerJoinIn": obj("加入阵营", map[string]any{
			"id":      si("活动 ID"),
			"camp_id": si("阵营"),
		}),
		"CheerSubmitIn": obj("提交加油", map[string]any{
			"id":    si("活动 ID"),
			"count": si("数量。不填当 1"),
		}),
		"CheerSubmitOut": obj("加油结果", map[string]any{
			"added":    si("这次加的"),
			"cheer":    si("个人总值"),
			"progress": si("阵营进度"),
			"activity": ref("Activity"),
		}),
		"CheerClaimIn": obj("领加油档", map[string]any{
			"id":   si("活动 ID"),
			"tier": si("档位"),
		}),
		"RecallPerson": obj("召回名单一人", map[string]any{
			"gid":          si("gid"),
			"name":         ss("昵称"),
			"avatar":       ss("头像"),
			"level":        si("等级"),
			"open_id":      ss("openid"),
			"offline_days": si("离线天数。可召回名单才有"),
			"last_login":   si("上次登录"),
			"recall_at":    si("召回时间。已召回名单才有"),
		}),
		"RecallListOut": obj("召回名单", map[string]any{
			"list": arr(ref("RecallPerson"), "名单"),
		}),
		"CharityFlower": obj("公益花", map[string]any{
			"love_id":      si("爱心道具"),
			"love_count":   si("爱心数量"),
			"personal":     si("个人积分"),
			"global":       si("全服积分"),
			"max_global":   si("全服上限"),
			"share_status": si("分享状态"),
			"share_reward": arr(ref("Item"), "分享奖"),
			"tiers":        arr(ref("CharityTier"), "个人档"),
			"global_tiers": arr(ref("CharityTier"), "全服档"),
			"can_donate":   sb("能不能捐"),
			"agreed":       sb("已同意合规"),
		}),
		"CharityTier": obj("公益花档", map[string]any{
			"need":    si("所需积分"),
			"rewards": arr(ref("Item"), "奖励"),
			"reached": sb("已达"),
			"claimed": sb("已领"),
		}),
		"CharityClaimIn": obj("领公益花档", map[string]any{
			"id":    si("活动 ID"),
			"score": si("个人积分档"),
		}),
		"CharityAgreeIn": obj("公益花合规", map[string]any{
			"id":     si("活动 ID"),
			"agreed": sb("是否同意"),
		}),
		"CharityDonateOut": obj("捐爱心", map[string]any{
			"consumed": si("花掉的爱心"),
			"added":    si("加的积分"),
			"personal": si("个人积分"),
			"global":   si("全服积分"),
			"items":    arr(ref("Item"), "奖励"),
			"activity": ref("Activity"),
		}),
		"CharityXhhOut": obj("公益花星辉回", map[string]any{
			"num":         si("数量"),
			"code":        ss("单号"),
			"trans":       ss("流水"),
			"business_id": ss("业务号"),
			"items":       arr(ref("Item"), "奖励"),
			"activity":    ref("Activity"),
		}),
		"DropPreview": obj("活动掉落预览", map[string]any{
			"id":          si("展示 ID"),
			"item_id":     si("物品"),
			"desc":        ss("说明"),
			"daily_limit": si("每日上限"),
			"dropped":     si("已掉"),
			"item":        ref("Item"),
		}),
		"LotteryIn": obj("雨落成诗采集", map[string]any{
			"id":       si("活动 ID。从 Activity/List 里带 lottery 的那条取"),
			"host_gid": si("可采集的农场。看 weather.can_collect"),
			"free":     si("免费次数"),
			"paid":     si("付费次数"),
		}),
		"LotteryHit": obj("抽奖单次", map[string]any{
			"goods_id":  si("商品 ID"),
			"items":     arr(ref("Item"), "这次的物品"),
			"quality":   si("品质"),
			"guarantee": sb("是否保底"),
		}),
		"LotteryOut": obj("雨落成诗采集结果", map[string]any{
			"items":    arr(ref("Item"), "抽到的合计"),
			"costs":    arr(ref("Item"), "花掉的"),
			"partial":  sb("只抽了一部分"),
			"results":  arr(ref("LotteryHit"), "每次结果"),
			"activity": ref("Activity"),
		}),
		"BrewStartIn": obj("开始酿酒", map[string]any{
			"id":    si("活动 ID"),
			"items": arr(obj("投入", map[string]any{"uid": si("背包格子"), "count": si("数量")}), "投入。uid 是格子"),
		}),
		"BrewStartOut": obj("开酿结果", map[string]any{
			"value":    si("投入后的值"),
			"activity": ref("Activity"),
		}),
		"BrewStepOut": obj("酿酒一步", map[string]any{
			"step":       si("当前步"),
			"multiplier": si("倍率"),
			"amount":     si("增量"),
			"finished":   sb("是否走完"),
			"activity":   ref("Activity"),
		}),
		"BrewClaimIn": obj("领酿酒", map[string]any{
			"id":         si("活动 ID"),
			"claim_type": si("1 普通 2 分享。不填当 1"),
		}),
		"InviteIn": obj("领邀新档", map[string]any{
			"id":          si("活动 ID"),
			"reward_type": si("1 邀请 2 成长"),
		}),
		"GiftIn": obj("送礼", map[string]any{
			"id":          si("活动 ID"),
			"gid":         si("好友"),
			"msg_text_id": si("附言文案 ID"),
		}),
		"MysteryGoods": obj("神秘商人商品", map[string]any{
			"id":       si("卡片 ID，购买用这个"),
			"item_id":  si("物品类型"),
			"quality":  si("品质"),
			"count":    si("数量"),
			"currency": si("货币类型"),
			"price":    si("现价"),
			"discount": si("折扣"),
			"bought":   sb("已买"),
			"original": si("原价"),
		}),
		"MysteryShop": obj("神秘商人", map[string]any{
			"present": sb("在不在"),
			"start":   si("出现时间"),
			"end":     si("离开时间"),
			"goods":   arr(ref("MysteryGoods"), "货架"),
		}),
		"MysteryAutoIn": obj("扫货架", map[string]any{
			"currency": si("只买这种货币。0 不限"),
		}),
		"PassLevel": obj("战令某一级", map[string]any{
			"level":   si("等级"),
			"free":    arr(ref("Item"), "免费档"),
			"premium": arr(ref("Item"), "付费档"),
			"key":     sb("关键档"),
			"tag":     ss("标签"),
		}),
		"BattlePass": obj("战令", map[string]any{
			"id":              si("战令 ID"),
			"name":            ss("名字"),
			"desc":            ss("说明"),
			"level":           si("等级"),
			"max_level":       si("满级"),
			"exp":             si("经验"),
			"level_exp":       si("本级经验"),
			"next_exp":        si("下级所需"),
			"premium":         sb("是否付费线"),
			"free_claimed":    si("免费线已领到哪"),
			"premium_claimed": si("付费线已领到哪"),
			"price":           si("付费线价格"),
			"levels":          arr(ref("PassLevel"), "各档奖励"),
		}),
		"SeasonActivity": obj("赛季活动简介", map[string]any{
			"id":    si("活动 ID"),
			"type":  si("类型"),
			"name":  ss("名字"),
			"start": si("开始，Unix 秒"),
			"end":   si("结束，Unix 秒"),
		}),
		"Season": obj("赛季", map[string]any{
			"id":          si("赛季 ID"),
			"name":        ss("名字"),
			"phase":       si("阶段"),
			"preheat":     si("预热开始"),
			"start":       si("开始，Unix 秒。千星游记赛季号 2026072700。礼包 2026-07-29 10:00 ~ 2026-08-27 23:59，以这里为准"),
			"end":         si("结束，Unix 秒。本地配置没有结束日，以这里为准"),
			"server_time": si("服务端时间"),
			"activities":  arr(ref("SeasonActivity"), "本赛季活动"),
			"next":        ref("Season"),
			"pass":        ref("BattlePass"),
		}),
		"PassClaimOut": obj("领战令", map[string]any{
			"items":    arr(ref("Item"), "领到的"),
			"levels":   arr(si(""), "刚领的等级"),
			"pass":     ref("BattlePass"),
			"overflow": sb("背包满"),
		}),
		"MysteryBuyOut": obj("买神秘商人", map[string]any{
			"items": arr(ref("Item"), "购得"),
			"goods": ref("MysteryGoods"),
		}),
		"MallIn": obj("商城槽", map[string]any{
			"slot": si("槽位。不填当 1"),
		}),
		"MallBuyIn": obj("买商城", map[string]any{
			"id":  si("商品 ID"),
			"num": si("数量。不填当 1"),
		}),
		"Product": obj("商城商品", map[string]any{
			"id":         si("商品 ID"),
			"name":       ss("名字"),
			"num":        si("数量"),
			"status":     si("状态"),
			"available":  sb("能不能买/领"),
			"goods_type": si("1 免费 2 付费"),
			"end_time":   si("结束时间"),
			"price":      ref("Item"),
			"rewards":    arr(ref("Item"), "奖励"),
			"bought":     si("已买"),
			"limit":      si("限购"),
			"discount":   ss("折扣文案"),
			"pic":        ss("图标"),
			"countdown":  sb("显示倒计时"),
		}),
		"MallProfile": obj("商城档位", map[string]any{
			"id":   si("商城 ID"),
			"type": si("类型"),
		}),
		"MonthCard": obj("月卡", map[string]any{
			"id":             si("月卡 ID"),
			"claimable":      sb("今天能不能领"),
			"days":           si("剩余天数"),
			"total_days":     si("总天数"),
			"claimed_amount": si("已领数量。0 未领"),
			"expire_seconds": si("过期相关秒数"),
			"total_count":    si("总奖励数量"),
			"pay_id":         ss("字符串商品 ID"),
			"rewards":        arr(ref("Item"), "每日奖励"),
			"purchase_cost":  ref("Item"),
			"claimable2":     sb("与 claimable 同步的可领标记"),
		}),
		"MonthCardClaimOut": obj("领月卡", map[string]any{
			"items": arr(ref("Item"), "领到的"),
			"card":  ref("MonthCard"),
		}),
		"RedPacket": obj("红包", map[string]any{
			"id":           si("活动 ID"),
			"claimed":      sb("今日已领"),
			"status":       si("活动状态。原样透出，不解释枚举"),
			"can_claim":    sb("今日未领且 status 非 0"),
			"name":         ss("活动名"),
			"desc":         ss("说明"),
			"time":         ss("时间文案"),
			"instructions": ss("领取说明"),
		}),
		"RedPacketClaimOut": obj("领红包", map[string]any{
			"status": si("领取结果状态"),
			"items":  arr(ref("Item"), "领到的一件"),
		}),
		"VisitLog": obj("来访记录", map[string]any{
			"time":       si("时间"),
			"action":     si("1浇水 2除虫 3除草 4偷菜 5放虫 6放草"),
			"gid":        si("来访人"),
			"name":       ss("昵称"),
			"avatar_url": ss("头像"),
			"crop_id":    si("作物/果实"),
			"crop_count": si("数量"),
			"times":      si("次数"),
			"from_type":  si("来源类型"),
			"level":      si("等级"),
		}),
		"VisitPopup": obj("来访弹窗", map[string]any{
			"unread":     sb("有未读"),
			"last_read":  si("上次已读时间"),
			"need_popup": sb("要不要弹"),
		}),
		"VisitPageIn": obj("分页来访", map[string]any{
			"page": si("页码。不填当 1"),
		}),
		"VisitDeleteIn": obj("删来访", map[string]any{
			"ids": arr(si(""), "记录 ID"),
		}),
		"AlbumIn": obj("图鉴筛选", map[string]any{
			"type":   si("1 普通 2 超变。不填当 1"),
			"rarity": si("稀有度。0 全部"),
		}),
		"AlbumItem": obj("图鉴条目", map[string]any{
			"fruit_id": si("果实 ID"),
			"rarity":   si("稀有度"),
			"unlocked": sb("已解锁"),
			"progress": si("进度"),
			"layer":    si("层级"),
			"new":      sb("新解锁未查看"),
			"rewards":  arr(ref("Item"), "奖励"),
		}),
		"Album": obj("图鉴", map[string]any{
			"items":     arr(ref("AlbumItem"), "条目"),
			"progress":  si("总进度"),
			"level":     si("当前图鉴等级"),
			"rewards":   arr(ref("Item"), "总奖励预览"),
			"rarities":  arr(si(""), "稀有度筛选值"),
			"type":      si("1 普通 2 超变"),
			"next":      si("距下一级进度"),
			"claimable": sb("有可领"),
			"claimed":   sb("有已领"),
			"buffs":     arr(ref("Buff"), "当前加成"),
			"next_buff": ref("Buff"),
		}),
		"Buff": obj("加成", map[string]any{
			"id":    si("属性"),
			"value": si("值"),
			"extra": si("附加"),
		}),
		"AlbumClaimOut": obj("领图鉴", map[string]any{
			"items":  arr(ref("Item"), "领到的"),
			"levels": arr(si(""), "刚领的等级"),
			"level":  si("当前等级"),
			"next":   arr(ref("Item"), "下一级预览"),
		}),
		"AlbumLevel": obj("图鉴等级", map[string]any{
			"level":     si("等级"),
			"need":      si("所需"),
			"rewards":   arr(ref("Item"), "奖励"),
			"can_claim": sb("可领"),
			"claimed":   sb("已领"),
		}),
		"AlbumLevels": obj("图鉴等级列表", map[string]any{
			"level":    si("当前等级"),
			"progress": si("总经验"),
			"levels":   arr(ref("AlbumLevel"), "普通"),
			"extra":    arr(ref("AlbumLevel"), "超变"),
		}),
		"Dog": obj("狗", map[string]any{
			"id":        si("狗 ID"),
			"name":      ss("名字"),
			"protect":   si("护院值"),
			"owned":     sb("已拥有"),
			"activated": sb("已激活"),
			"price":     si("售价"),
			"expire":    si("过期时间。0 永久"),
			"lost_min":  si("被偷金币下限"),
			"lost_max":  si("被偷金币上限"),
		}),
		"DogFood": obj("狗粮", map[string]any{
			"id":      si("狗粮物品 ID，喂的时候带 food_id"),
			"seconds": si("一份加多少秒"),
			"count":   si("库存"),
		}),
		"DogSkill": obj("技能", map[string]any{
			"id":     si("技能 ID"),
			"dog_id": si("哪只狗"),
			"used":   si("今日已触发"),
			"max":    si("每日上限。-1 不限"),
		}),
		"DogYard": obj("护主犬", map[string]any{
			"dogs":      arr(ref("Dog"), "狗"),
			"deployed":  si("出战的狗 ID"),
			"food_left": si("狗粮剩余秒"),
			"food_max":  si("狗粮上限秒"),
			"foods":     arr(ref("DogFood"), "粮库存"),
			"new_log":   sb("有新护院日志"),
			"pending":   si("待领礼物数"),
			"skills":    arr(ref("DogSkill"), "技能"),
		}),
		"FeedIn": obj("喂狗", map[string]any{
			"food_id": si("狗粮 ID，从 Dog/Info 取"),
			"count":   si("份数。不填当 1"),
		}),
		"PageIn": obj("翻页", map[string]any{
			"from":  si("起始"),
			"count": si("条数"),
		}),
		"ProtectLog": obj("护院日志", map[string]any{
			"time":        si("时间"),
			"gid":         si("对方"),
			"name":        ss("昵称"),
			"avatar_url":  ss("头像"),
			"level":       si("等级"),
			"online":      sb("在线"),
			"last_online": si("上次在线"),
			"read":        sb("已读"),
			"authorized":  si("实名状态"),
			"dog_id":      si("哪只狗"),
			"dog_name":    ss("狗名"),
			"count":       si("次数"),
			"gold":        si("扣的金币"),
			"record_type": si("记录类型"),
			"skill_id":    si("技能 ID"),
			"skill":       ss("技能"),
			"trigger":     si("触发类型"),
		}),
		"DogGiftOut": obj("领技能礼物", map[string]any{
			"items":       arr(ref("Item"), "领到的"),
			"compensated": arr(ref("Item"), "背包满补偿"),
			"claimed":     si("本次领了几个"),
			"pending":     si("还剩几个"),
		}),
		"DogLogsOut": obj("护院日志列表", map[string]any{
			"logs":  arr(ref("ProtectLog"), "日志"),
			"total": si("总数"),
		}),
		"DeployOut": obj("出战/收回", map[string]any{
			"deployed":  si("现在出战的狗。0 是没有"),
			"previous":  si("出战时：之前出战的狗"),
			"withdrawn": si("收回时：被收回的狗"),
		}),
		"DogBuyIn": obj("买狗", map[string]any{
			"id":    si("狗 ID"),
			"price": si("价格。不填从 Dog/Info 取"),
		}),
		"DogBuyOut": obj("买狗结果", map[string]any{
			"dog":  ref("Dog"),
			"cost": arr(ref("Item"), "花费"),
		}),
		"Bulletin": obj("公告", map[string]any{
			"id":       si("公告 ID"),
			"title":    ss("标题"),
			"read":     sb("已读"),
			"forced":   sb("强制弹"),
			"pop_type": si("弹出类型"),
			"banner":   ss("横幅图"),
		}),
		"BulletinDetail": obj("公告正文", map[string]any{
			"title":         ss("标题"),
			"content":       ss("正文"),
			"start":         ss("开始"),
			"end":           ss("结束"),
			"banner":        ss("横幅"),
			"detail_banner": ss("详情横幅"),
		}),
		"Mutant": obj("变异宝典条目", map[string]any{
			"id":          si("条目 ID"),
			"start":       si("开始时间"),
			"end":         si("结束时间"),
			"activity_id": si("关联活动"),
			"red_point":   sb("红点"),
		}),
		"Career": obj("生涯", map[string]any{
			"gid":        si("查的是谁"),
			"name":       ss("昵称"),
			"level":      si("等级"),
			"exp":        si("经验"),
			"avatar_url": ss("头像"),
			"signature":  ss("签名"),
			"harvested":  si("总收获"),
			"stolen":     si("总被偷"),
			"remark":     ss("备注"),
			"gender":     si("性别"),
			"authorized": si("实名状态"),
			"items":      arr(ref("Item"), "收获过的物品统计"),
		}),
		"RankIn": obj("排行榜", map[string]any{
			"type": si("1 等级 2 金币 3 图鉴。不填当 1"),
			"page": si("页码。不填当 1"),
		}),
		"RankItem": obj("榜上一人", map[string]any{
			"gid":        si("gid"),
			"name":       ss("昵称"),
			"value":      si("榜值。等级榜是等级，金币榜是金币"),
			"rank":       si("名次"),
			"avatar_url": ss("头像"),
			"level":      si("等级"),
		}),
		"RankBoard": obj("排行榜", map[string]any{
			"items": arr(ref("RankItem"), "本页"),
			"total": si("总人数"),
		}),
		"TypeIn": obj("按类型筛", map[string]any{
			"type": si("类型。0 全部"),
		}),
		"Avatar": obj("头像框", map[string]any{
			"id":       si("头像框 ID"),
			"type":     si("类型"),
			"count":    si("数量"),
			"priority": si("优先级"),
			"new":      sb("新获得未查看"),
			"expire":   si("过期时间。0 永久"),
		}),
		"AvatarEquipIn": obj("穿脱头像框", map[string]any{
			"id":  si("头像框。卸下可 0"),
			"off": sb("true 卸下"),
		}),
		"Skin": obj("皮肤", map[string]any{
			"id":       si("皮肤 ID"),
			"slot":     si("槽位"),
			"equipped": sb("穿着"),
			"expire":   si("过期时间"),
		}),
		"SkinEquipIn": obj("换皮肤", map[string]any{
			"current_id": si("当前皮肤"),
			"id":         si("新皮肤。0 卸下"),
		}),
		"DropReward": obj("掉落档", map[string]any{
			"id":      si("档 ID"),
			"count":   si("数量"),
			"chance":  si("权重/概率"),
			"claimed": sb("已领"),
		}),
		"Drop": obj("随机掉落活动", map[string]any{
			"id":      si("活动 ID"),
			"name":    ss("名字"),
			"status":  si("状态"),
			"start":   si("开始"),
			"end":     si("结束"),
			"dropped": si("已掉"),
			"limit":   si("上限"),
			"rewards": arr(ref("DropReward"), "档位"),
		}),
		"SolarTerm": obj("节气", map[string]any{
			"id":      si("节气 ID，领取用这个"),
			"name":    ss("名字，如小暑"),
			"status":  si("1未到 2可领 3已领 4过期未领 5过期已领"),
			"start":   si("窗口开始"),
			"end":     si("窗口结束"),
			"rewards": arr(ref("Item"), "奖励"),
		}),
		"SolarBasic": obj("节气赛季配置", map[string]any{
			"id":     si("配置 ID"),
			"season": si("赛季"),
			"desc":   ss("说明"),
			"events": arr(si(""), "包含的节气 ID"),
		}),
		"SolarOut": obj("节气列表", map[string]any{
			"terms":       arr(ref("SolarTerm"), "节气"),
			"server_time": si("服务端时间"),
			"basic":       ref("SolarBasic"),
			"basics":      arr(ref("SolarBasic"), "各赛季配置"),
		}),
		"RedDot": obj("红点", map[string]any{
			"red_dot": sb("有没有红点"),
		}),
		"AchieveIn": obj("成就域", map[string]any{
			"kind": si("域种类"),
			"id":   si("域 ID"),
		}),
		"AchieveGoalIn": obj("领成就目标", map[string]any{
			"kind":    si("域种类"),
			"id":      si("域 ID"),
			"goal_id": si("目标 ID"),
		}),
		"AchieveGoal": obj("成就目标", map[string]any{
			"id":       si("目标 ID"),
			"cond":     si("条件类型"),
			"progress": si("进度"),
			"total":    si("所需"),
			"claimed":  sb("已领"),
			"unlock":   si("解锁时间"),
			"category": si("分类"),
			"exp":      si("领取后加的域经验"),
			"need":     arr(ref("Item"), "需要消耗"),
			"desc":     ss("描述"),
			"sort":     si("排序"),
		}),
		"AchieveGoalOut": obj("领成就目标", map[string]any{
			"exp":    si("这次加的域经验。不是物品"),
			"before": si("领之前的域等级"),
			"after":  si("领之后的域等级"),
			"scope":  ref("AchieveScope"),
		}),
		"SolarClaimOut": obj("领节气", map[string]any{
			"items": arr(ref("Item"), "领到的"),
			"event": ref("SolarTerm"),
		}),
		"AchieveLevel": obj("成就等级", map[string]any{
			"level":   si("等级"),
			"need":    si("所需"),
			"claimed": sb("已领"),
			"rewards": arr(ref("Item"), "奖励"),
		}),
		"AchieveScope": obj("成就域", map[string]any{
			"kind":          si("种类"),
			"id":            si("域 ID"),
			"level":         si("等级"),
			"exp":           si("经验"),
			"next":          si("下级所需"),
			"claimed_level": si("已领到哪一级"),
			"goals":         arr(ref("AchieveGoal"), "目标"),
			"levels":        arr(ref("AchieveLevel"), "等级奖"),
		}),
		"CleanFarmEventOut": obj("清农场级使坏", map[string]any{
			"events":  arr(ref("FarmSocial"), "官方 Farming 回包没有事件列表，通常为空"),
			"rewards": arr(ref("FarmReward"), "奖励，来自 Farming.farm_rewards"),
		}),
		"BlockAppsIn": obj("拒收申请", map[string]any{
			"block": sb("true 拒收好友申请"),
		}),
		"BlockAppsOut": obj("拒收申请结果", map[string]any{
			"block": sb("当前是否拒收"),
		}),
		"WXRecommendIn": obj("微信推荐", map[string]any{
			"encrypted_data": ss("微信加密数据。可空"),
		}),
		"WXRecommendPageIn": obj("微信推荐分页", map[string]any{
			"offset":    si("偏移"),
			"page_size": si("每页。不填当 20"),
		}),
		"WXRecommendPlayer": obj("微信推荐玩家", map[string]any{
			"gid":        si("gid"),
			"name":       ss("昵称"),
			"avatar_url": ss("头像"),
			"level":      si("等级"),
			"applied":    sb("已申请"),
		}),
		"WXRecommendOut": obj("微信推荐列表", map[string]any{
			"players":  arr(ref("WXRecommendPlayer"), "推荐"),
			"total":    si("总数"),
			"has_more": sb("还有下一页"),
		}),
		"WXApplyResult": obj("微信加好友结果", map[string]any{
			"gid":        si("目标 gid"),
			"success":    sb("是否成功"),
			"error_code": si("失败码"),
		}),
		"WXApplyOut": obj("微信批量加好友", map[string]any{
			"results": arr(ref("WXApplyResult"), "逐个结果"),
		}),
		"SkinSetIn": obj("穿套装", map[string]any{
			"skin_ids": arr(si(""), "皮肤 ID"),
		}),
		"SkinSetEffect": obj("套装特效", map[string]any{
			"set_id":      si("套装 ID"),
			"effect_type": si("特效类型"),
			"active":      sb("是否开启"),
		}),
		"SkinSetEffectIn": obj("开关套装特效", map[string]any{
			"set_id":      si("套装 ID"),
			"effect_type": si("特效类型"),
			"enabled":     sb("开或关"),
			"type_id":     si("类型 ID"),
			"param":       si("附加参数"),
		}),
		"BuyPassOut": obj("买高级战令", map[string]any{
			"success": sb("是否成功"),
			"items":   arr(ref("Item"), "购买奖励"),
			"pass":    ref("BattlePass"),
		}),
		"CookiesIn": obj("带 cookies", map[string]any{
			"cookies": ss("平台 cookies。可空"),
		}),
		"QQGroup": obj("已授权 QQ 群", map[string]any{
			"openid":     ss("群 openid"),
			"name":       ss("群名"),
			"avatar_url": ss("头像"),
			"bound":      si("已绑定人数"),
		}),
		"QQAuthGroupsOut": obj("已授权群", map[string]any{
			"groups":  arr(ref("QQGroup"), "群"),
			"cookies": ss("回写 cookies"),
		}),
		"QQRecommendIn": obj("推荐群", map[string]any{
			"class_name":   ss("分类"),
			"session_info": ss("翻页会话"),
			"scene_id":     si("场景"),
		}),
		"QQRecommendGroup": obj("推荐群", map[string]any{
			"openid":      ss("群 openid"),
			"name":        ss("群名"),
			"avatar_url":  ss("头像"),
			"join_auth":   ss("加群凭证"),
			"jump_schema": ss("跳转"),
			"bound":       si("已绑定人数"),
			"members":     si("成员数"),
		}),
		"QQRecommendOut": obj("推荐群列表", map[string]any{
			"groups":       arr(ref("QQRecommendGroup"), "群"),
			"ended":        sb("没有更多"),
			"pos":          si("位置"),
			"session_info": ss("下次翻页带上"),
		}),
		"QQBindIn": obj("绑定社群", map[string]any{
			"community_id": ss("社群 ID"),
		}),
		"QQCommunity": obj("社群", map[string]any{
			"openid":     ss("openid"),
			"name":       ss("名字"),
			"avatar_url": ss("头像"),
		}),
		"QQBindOut": obj("绑定结果", map[string]any{
			"community":      ref("QQCommunity"),
			"bound_at":       si("绑定时间"),
			"reward_claimed": sb("已领绑定奖"),
		}),
		"QQLeaveOut": obj("退出社群", map[string]any{
			"quit_left":      si("剩余可退次数"),
			"cooldown_until": si("冷却截止"),
		}),
		"QQCommunityOut": obj("社群信息", map[string]any{
			"community":    ref("QQCommunity"),
			"bound_at":     si("绑定时间"),
			"member_count": si("成员数"),
			"friends":      arr(ref("Friend"), "群内游戏好友"),
			"has_more":     sb("还有下一页"),
		}),
		"QQBindInfoOut": obj("绑定详情", map[string]any{
			"community":      ref("QQCommunity"),
			"bound_at":       si("绑定时间"),
			"cooldown_until": si("冷却截止"),
			"reward_claimed": sb("已领绑定奖"),
			"quit_left":      si("剩余可退次数"),
			"rewards":        arr(ref("Item"), "绑定奖预览"),
			"max_quit":       si("最多可退几次"),
			"cooldown_days":  si("冷却天数"),
		}),
		"QQRevokeIn": obj("撤销授权", map[string]any{
			"gid":          si("gid"),
			"community_id": ss("社群 ID"),
		}),
		"UIDIn": obj("背包格子", map[string]any{
			"uid": si("背包格子 uid，不是兑换码"),
		}),
		"GiftTokenOut": obj("使用礼包码道具", map[string]any{
			"source_type":      si("来源"),
			"present_order_id": ss("订单"),
			"redeem_code":      ss("兑换码。回包才有"),
			"platform_url":     ss("平台链接"),
			"display_name":     ss("展示名"),
			"package_info":     ss("包裹信息"),
			"out_bill_no":      ss("转账单号"),
			"transfer_amount":  si("转账金额"),
			"mch_id":           ss("商户号"),
		}),
		"GiftHistoryIn": obj("礼包领取历史", map[string]any{
			"source_type": si("来源。0 全部"),
			"page":        si("页码。不填当 1"),
			"page_size":   si("每页。不填当 20"),
		}),
		"GiftClaimRecord": obj("礼包领取记录", map[string]any{
			"claim_id":         ss("领取 ID"),
			"item_id":          si("物品"),
			"source_type":      si("来源"),
			"status":           si("状态"),
			"assigned_time":    si("发放时间"),
			"expire_time":      si("过期"),
			"title":            ss("标题"),
			"subtitle":         ss("副标题"),
			"detail_url":       ss("详情"),
			"code":             ss("码"),
			"present_order_id": ss("订单"),
			"wx_activity_id":   ss("微信活动"),
		}),
		"GiftHistoryOut": obj("礼包历史", map[string]any{
			"records": arr(ref("GiftClaimRecord"), "记录"),
			"total":   si("总数"),
		}),
		"TransferIn": obj("转账查询", map[string]any{
			"out_bill_no": ss("转账单号"),
		}),
		"TransferOut": obj("转账状态", map[string]any{
			"state":       si("状态"),
			"fail_reason": ss("失败原因"),
		}),
		"FollowGiftOut": obj("关注有礼状态", map[string]any{
			"followed": sb("已关注"),
			"claimed":  sb("已领"),
			"red_dot":  sb("红点"),
		}),
		"FollowGiftIn": obj("标记关注", map[string]any{
			"followed": sb("是否已关注"),
		}),
		"RechargeRange": obj("返利档", map[string]any{
			"min":   si("充值下限"),
			"max":   si("充值上限"),
			"ratio": si("返利比例"),
		}),
		"RechargeBonusOut": obj("充值返利配置", map[string]any{
			"active": sb("活动是否开"),
			"start":  si("开始"),
			"end":    si("结束"),
			"unlock": si("解锁条件"),
			"ranges": arr(ref("RechargeRange"), "档位"),
		}),
		"RechargeDataOut": obj("充值返利进度", map[string]any{
			"recharged": si("已充"),
			"returned":  si("已返"),
		}),
		"DisplayIn": obj("改展示资料", map[string]any{
			"name":       ss("昵称"),
			"avatar_url": ss("头像"),
			"signature":  ss("签名"),
			"gender":     si("性别"),
			"remark":     ss("备注"),
		}),
		"DisplayOut": obj("展示资料", map[string]any{
			"name":       ss("昵称"),
			"avatar_url": ss("头像"),
			"signature":  ss("签名"),
			"gender":     si("性别"),
			"remark":     ss("备注"),
			"authorized": si("实名状态"),
		}),
		"SettingsKeysIn": obj("读设置", map[string]any{
			"keys": arr(si(""), "要读的设置键。空则全读"),
		}),
		"UserSettings": obj("用户设置", map[string]any{
			"disable_nudge":           sb("关戳一戳"),
			"disable_month_card":      sb("关月卡提示"),
			"disable_qq_subscribe":    sb("关 QQ 订阅"),
			"disable_wx_recommend":    sb("关微信推荐"),
			"disable_offline_summary": sb("关离线摘要"),
			"allow_ark_visit":         sb("允许 ARK 来访"),
		}),
		"DeleteAccountIn": obj("删号", map[string]any{
			"name":      ss("实名"),
			"cert_id":   ss("证件号"),
			"cert_type": si("证件类型"),
		}),
		"DeleteAccountOut": obj("删号结果", map[string]any{
			"success":      sb("是否受理"),
			"msg":          ss("说明"),
			"request_time": si("申请时间"),
			"delete_time":  si("预计删除时间"),
		}),
		"DecryptIn": obj("解密开放数据", map[string]any{
			"encrypted_data": ss("加密串"),
		}),
		"QQAuthIn": obj("QQ 好友推荐授权", map[string]any{
			"authorized": sb("是否授权"),
		}),
		"QQAuthOut": obj("QQ 好友推荐授权结果", map[string]any{
			"authorized": si("授权状态"),
		}),
		"ReportFlowIn": obj("客户端流水", map[string]any{
			"os_type":       si("系统"),
			"plat_type":     si("平台"),
			"open_id":       ss("openid"),
			"gid":           si("gid"),
			"name":          ss("昵称"),
			"now":           si("时间"),
			"level":         si("等级"),
			"flow_type":     si("流水类型"),
			"flow_type_str": ss("流水类型名"),
			"param_int1":    si("整型参数 1"),
			"param_int2":    si("整型参数 2"),
			"param_int3":    si("整型参数 3"),
			"param_int4":    si("整型参数 4"),
			"param_int5":    si("整型参数 5"),
			"param_str6":    ss("字符串参数 6"),
			"param_str7":    ss("字符串参数 7"),
			"param_str8":    ss("字符串参数 8"),
			"param_str9":    ss("字符串参数 9"),
			"param_str10":   ss("字符串参数 10"),
		}),
		"BatchReportFlowIn": obj("批量流水", map[string]any{
			"flows": arr(ref("ReportFlowIn"), "流水"),
		}),
		"BatchReportFlowOut": obj("批量流水结果", map[string]any{
			"success_count": si("成功数"),
			"fail_count":    si("失败数"),
		}),
		"ReportUserIn": obj("举报", map[string]any{
			"gid":          si("被举报人"),
			"category":     si("分类"),
			"reasons":      arr(si(""), "原因"),
			"scene":        si("场景"),
			"desc":         ss("描述"),
			"content":      ss("内容"),
			"pics":         arr(ss(""), "图"),
			"videos":       arr(ss(""), "视频"),
			"voices":       arr(ss(""), "语音"),
			"group_id":     ss("群 ID"),
			"group_name":   ss("群名"),
			"battle_id":    ss("对局 ID"),
			"battle_time":  si("对局时间"),
			"entrance":     si("入口"),
			"msg_board_id": ss("留言板 ID"),
		}),
		"ReportUserOut": obj("举报结果", map[string]any{
			"success":  sb("是否成功"),
			"msg":      ss("说明"),
			"trace_id": ss("追踪号"),
		}),
		"QQVipDailyOut": obj("QQ 会员每日礼状态", map[string]any{
			"is_qq_vip":     sb("是不是 QQ 会员"),
			"can_claim":     sb("今天能不能领"),
			"claimed_today": sb("今天已经领过"),
			"rewards":       arr(ref("Item"), "每日礼预览"),
		}),
		"QQVipClaimDailyIn": obj("领 QQ 会员每日礼", map[string]any{
			"config_id": si("配置 ID。可空"),
		}),
		"QQVipClaimDailyOut": obj("领每日礼结果", map[string]any{
			"rewards": arr(ref("Item"), "本次奖励"),
		}),
		"QQVipRefreshOut": obj("刷新会员信息", map[string]any{
			"is_qq_vip": sb("是不是 QQ 会员"),
			"vip_level": si("会员等级"),
		}),
		"QQVipConfig": obj("QQ 会员奖励档", map[string]any{
			"type":              si("档类型"),
			"rewards":           arr(ref("Item"), "奖励"),
			"is_enable":         sb("是否启用"),
			"season_id":         si("赛季"),
			"id":                si("配置 ID"),
			"reward_multiplier": si("倍率"),
			"act_start_time":    si("开始"),
			"act_end_time":      si("结束"),
		}),
		"QQVipRewardsStatusOut": obj("QQ 会员奖励状态", map[string]any{
			"is_qq_vip":         sb("是不是 QQ 会员"),
			"can_claim":         sb("每日礼能否领"),
			"claimed_today":     sb("每日礼今天已领"),
			"rewards_can_claim": sb("会员奖励能否领"),
			"active_configs":    arr(ref("QQVipConfig"), "当前档"),
			"has_redpoint":      sb("红点"),
		}),
		"QQVipClaimRewardsIn": obj("领 QQ 会员奖励", map[string]any{
			"config_ids": arr(si(""), "配置 ID"),
		}),
		"QQVipClaimRewardsOut": obj("领会员奖励结果", map[string]any{
			"granted_skin_item_ids":         arr(si(""), "发下的皮肤物品 ID"),
			"granted_avatar_frame_item_ids": arr(si(""), "发下的头像框物品 ID"),
			"rewards":                       arr(ref("Item"), "其他奖励"),
		}),
		"MarqueeMsg": obj("跑马灯一条", map[string]any{
			"uuid":          si("消息 ID"),
			"config_id":     si("配置"),
			"expire_time":   si("过期"),
			"type":          si("类型"),
			"content":       ss("正文"),
			"priority":      si("优先级"),
			"display_count": si("展示次数"),
		}),
		"MarqueeOut": obj("跑马灯列表", map[string]any{
			"msgs": arr(ref("MarqueeMsg"), "消息"),
		}),
		"SystemOpenIn": obj("查系统解锁", map[string]any{
			"system_name": si("系统编号"),
		}),
		"SystemOpenOut": obj("系统解锁结果", map[string]any{
			"unlocked": sb("是否已开"),
		}),
		"MutantOpenInfoOut": obj("变异系统开放奖励", map[string]any{
			"tips":    ss("提示"),
			"rewards": arr(ref("Item"), "奖励"),
		}),
		"QQSubscribeItem": obj("QQ 订阅条目", map[string]any{
			"id":         si("模板或场景 ID"),
			"subscribed": sb("是否已订"),
		}),
		"QQSubscribeOut": obj("QQ 订阅状态", map[string]any{
			"status":     si("标量状态。旧回包才有"),
			"subscribed": sb("有没有订过"),
			"items":      arr(ref("QQSubscribeItem"), "map 形态的逐条状态"),
		}),
		"WXTemplateStatus": obj("微信订阅模板", map[string]any{
			"template_id": ss("模板 ID"),
			"subscribed":  sb("是否已订"),
		}),
		"WXSubscribeIn": obj("写微信订阅", map[string]any{
			"templates": arr(ref("WXTemplateStatus"), "模板"),
		}),
		"WXSubscribeOut": obj("微信订阅状态", map[string]any{
			"templates": arr(ref("WXTemplateStatus"), "模板"),
		}),
		"ModerateTextIn": obj("审文本", map[string]any{
			"text":   ss("待审文本"),
			"reason": ss("场景"),
		}),
		"ModerateTextOut": obj("文本审核结果", map[string]any{
			"result_text": ss("审核后文本，可能带替换"),
			"is_dirty":    sb("是否命中"),
			"reason":      ss("原因"),
		}),
		"ModerateTextBatchIn": obj("批量审文本", map[string]any{
			"text_items": arr(ref("ModerateTextIn"), "待审"),
		}),
		"ModerateTextBatchOut": obj("批量文本审核", map[string]any{
			"text_items": arr(ref("ModerateTextOut"), "结果"),
		}),
		"ModeratePicIn": obj("审图片", map[string]any{
			"pic_url": ss("图片 URL"),
			"reason":  ss("场景"),
		}),
		"ModeratePicOut": obj("图片审核结果", map[string]any{
			"result_url": ss("审核后 URL"),
			"is_dirty":   sb("是否命中"),
			"dirty_type": si("命中类型"),
			"reason":     ss("原因"),
		}),
		"ModeratePicBatchIn": obj("批量审图片", map[string]any{
			"pic_items": arr(ref("ModeratePicIn"), "待审"),
		}),
		"ModeratePicBatchOut": obj("批量图片审核", map[string]any{
			"pic_items": arr(ref("ModeratePicOut"), "结果"),
		}),
	}
}

func listData(key, item string, desc string) map[string]any {
	return obj(desc, map[string]any{key: arr(ref(item), desc)})
}

func itemsData() map[string]any {
	return listData("items", "Item", "得到的物品")
}

func landsData() map[string]any {
	return listData("lands", "Land", "地块")
}

func emptyData() map[string]any {
	return obj("没有业务字段", map[string]any{})
}

func openAPIPaths() map[string]any {
	return map[string]any{
		"/System/Ping":   docOp("System 系统", "探活", "不登录也能打。", "", obj("探活", map[string]any{"pong": sb("恒为 true")})),
		"/System/Status": docOp("System 系统", "登录状态", "看有没有登录、当前在谁家、登录天气。ace 是长会话计数：uploads 是 Ace.AntiData 成功次数，status_reports 大约 150 秒后才有。登录后自动跑，没有 /Ace 接口。", "", ref("Status")),
		"/YYB/Accounts":  docOp("YYB 应用宝", "已保存账号", "扫过码的微信账号。", "", listData("accounts", "YYBAccount", "账号")),
		"/YYB/QR":        docOp("YYB 应用宝", "出登录二维码", "微信扫。image 是 data URL。", "", ref("YYBQROut")),
		"/YYB/Image": map[string]any{"get": map[string]any{
			"tags":        []string{"YYB 应用宝"},
			"summary":     "二维码 JPEG",
			"description": "session_id 来自 YYB/QR。也可以直接用 QR 回包的 image。",
			"parameters": []any{map[string]any{
				"name": "session_id", "in": "query", "required": true,
				"schema": ss("扫码会话"),
			}},
			"responses": map[string]any{"200": map[string]any{
				"description": "JPEG",
				"content":     map[string]any{"image/jpeg": map[string]any{"schema": map[string]any{"type": "string", "format": "binary"}}},
			}},
		}},
		"/YYB/Poll":                  docOp("YYB 应用宝", "轮询扫码", "pending 没扫，scanned 已扫未确认，authorized 可以 Confirm。cancelled / expired / unknown 是终态。", "YYBSessionIn", ref("YYBPollOut")),
		"/YYB/Confirm":               docOp("YYB 应用宝", "确认扫码并保存账号", "authorized 之后调。会拉应用宝昵称和头像 URL。", "YYBSessionIn", ref("YYBAccount")),
		"/YYB/Refresh":               docOp("YYB 应用宝", "刷新登录态", "ref 空则刷第一条。status 必须是 alive 才能取 code。", "YYBRefIn", ref("YYBRefreshOut")),
		"/YYB/Code":                  docOp("YYB 应用宝", "取小程序 code", "ref 空则用第一条。过期会先刷新再重试。", "YYBRefIn", ref("YYBCodeOut")),
		"/YYB/Login":                 docOp("YYB 应用宝", "取 code 并登录网关", "内部先 YYB/Code 再 User/Login。缺 wasm 仍然失败。", "YYBRefIn", ref("User")),
		"/YYB/Delete":                docOp("YYB 应用宝", "删已保存账号", "只删本地 yyb.db，不是游戏删号。ref 必填。", "YYBRefIn", ref("YYBDeleteOut")),
		"/YYB/Profile":               docOp("YYB 应用宝", "再拉昵称和头像", "用已保存凭据打应用宝资料。ref 空则第一条。", "YYBRefIn", ref("YYBAccount")),
		"/YYB/Phone":                 docOp("YYB 应用宝", "取微信手机号", "协议 GetPhoneNumber。默认农场 appid。回包在 result。", "YYBRefIn", ref("YYBRawOut")),
		"/YYB/WXData":                docOp("YYB 应用宝", "微信云函数代理", "协议 OperateWXData。payload 必填，通常带 api_name。", "YYBWXDataIn", ref("YYBRawOut")),
		"/Resource/Lookup":           docOp("Resource 资源表", "按 ID 查名字", "回包里的 items[].id、seed_id、goods_id 都能查。同一个 ID 在不同表里含义不同，所以回的是数组，可用 table 收窄。", "ResLookupIn", ref("ResListOut")),
		"/Resource/Items":            docOp("Resource 资源表", "列配表", "按 table / type / keyword 筛。种子是 ItemInfo 里 type=5。不填 table 就跨表搜。", "ResListIn", ref("ResListOut")),
		"/Resource/Tables":           docOp("Resource 资源表", "有哪些表", "表名和行数，先看这个再决定查哪张。", "", ref("ResTablesOut")),
		"/Resource/Refresh":          docOp("Resource 资源表", "从官方 CDN 刷新", "拉最新配表并写本地缓存。游戏更新后内置表会过期，这时传 bundle_vers 覆盖。", "ResRefreshIn", ref("ResRefreshOut")),
		"/User/Login":                docOp("User 用户", "登录", "连游戏网关。code 可从 YYB/Code 拿。缺 wasm 直接失败。", "LoginIn", ref("User")),
		"/User/GetInfo":              docOp("User 用户", "自己资料", "缓存里的自己。", "", ref("User")),
		"/User/Brief":                docOp("User 用户", "查别人简要资料", "", "EnterIn", ref("User")),
		"/User/BatchInfo":            docOp("User 用户", "按 gid 批量查", "", "GIDsIn", listData("users", "User", "用户")),
		"/User/ArkClick":             docOp("User 用户", "ARK 点击上报", "点分享链的上报，不是加好友申请。回包为空。", "ArkIn", emptyData()),
		"/User/SetDisplay":           docOp("User 用户", "改展示资料", "昵称 / 头像 / 签名 / 性别 / 备注。", "DisplayIn", ref("DisplayOut")),
		"/User/Settings":             docOp("User 用户", "读用户设置", "keys 空则全读。", "SettingsKeysIn", ref("UserSettings")),
		"/User/SetSettings":          docOp("User 用户", "写用户设置", "六个开关一起发。", "UserSettings", ref("UserSettings")),
		"/User/DeleteAccount":        docOp("User 用户", "申请删号", "name 和 cert_id 必填。", "DeleteAccountIn", ref("DeleteAccountOut")),
		"/User/DecryptOpenData":      docOp("User 用户", "解密开放数据", "", "DecryptIn", obj("明文", map[string]any{"json_data": ss("解密后的 JSON")})),
		"/User/QQRecommendAuth":      docOp("User 用户", "QQ 好友推荐授权", "只发 authorized。", "QQAuthIn", ref("QQAuthOut")),
		"/User/ReportFlow":           docOp("User 用户", "上报客户端流水", "不是举报。回包为空。", "ReportFlowIn", emptyData()),
		"/User/BatchReportFlow":      docOp("User 用户", "批量上报流水", "", "BatchReportFlowIn", ref("BatchReportFlowOut")),
		"/User/Report":               docOp("User 用户", "举报玩家", "gid 必填。不是流水。", "ReportUserIn", ref("ReportUserOut")),
		"/User/Logout":               docOp("User 用户", "退出", "先发网关登出再断开。", "", emptyData()),
		"/User/Heartbeat":            docOp("User 用户", "网关心跳", "登录后也会每 25 秒自动发。可带 host_gid。", "RefreshIn", ref("HeartbeatOut")),
		"/Farm/Refresh":              docOp("Farm 农场", "全量刷新地块", "可带 host_gid 看别人家。带回 limits / events。", "RefreshIn", ref("LandOpOut")),
		"/Farm/RefreshLands":         docOp("Farm 农场", "增量刷新", "land_ids 空则不发包。", "RefreshLandsIn", landsData()),
		"/Farm/CleanSocial":          docOp("Farm 农场", "清地块上别人放的乌云/黄金虫", "item_ids=[5006] 清乌云。land_ids 从 Refresh.social_items 取。青蛙走 Farm/CleanEvents。", "CleanSocialIn", ref("LandOpOut")),
		"/Farm/Harvest":              docOp("Farm 农场", "收获", "", "HarvestIn", ref("HarvestOut")),
		"/Farm/Steal":                docOp("Farm 农场", "偷菜", "必须填好友 host_gid。会先预检。", "HarvestIn", ref("HarvestOut")),
		"/Farm/Plant":                docOp("Farm 农场", "种植", "回地块 / 次数 / 掉落。", "PlantIn", ref("LandOpOut")),
		"/Farm/Remove":               docOp("Farm 农场", "铲地", "", "RemoveIn", ref("LandOpOut")),
		"/Farm/Unlock":               docOp("Farm 农场", "解锁地块", "", "LandIDIn", ref("Land")),
		"/Farm/Upgrade":              docOp("Farm 农场", "升级地块", "", "LandIDIn", ref("Land")),
		"/Farm/Farming":              docOp("Farm 农场", "一键浇水除草杀虫", "可带 host_gid。清别人放的青蛙可带 item_ids=[5005]。乌云走 Farm/CleanSocial。", "LandOpIn", ref("LandOpOut")),
		"/Farm/Water":                docOp("Farm 农场", "浇水", "", "LandOpIn", ref("LandOpOut")),
		"/Farm/Weed":                 docOp("Farm 农场", "除草", "", "LandOpIn", ref("LandOpOut")),
		"/Farm/Bug":                  docOp("Farm 农场", "杀虫", "", "LandOpIn", ref("LandOpOut")),
		"/Farm/Fertilize":            docOp("Farm 农场", "施肥", "costs 是消耗的肥料。", "FertilizeIn", ref("LandOpOut")),
		"/Farm/PutInsects":           docOp("Farm 农场", "放虫", "必须填好友 host_gid。", "LandOpIn", ref("LandOpOut")),
		"/Farm/PutWeeds":             docOp("Farm 农场", "放草", "必须填好友 host_gid。", "LandOpIn", ref("LandOpOut")),
		"/Farm/PutSocial":            docOp("Farm 农场", "往别人家放使坏瓶", "官方走 Item.Use。青蛙 5005 不带地，乌云 5006 必须带地。自己家被放的：青蛙清 Farm/CleanEvents，乌云清 Farm/CleanSocial。", "PutSocialIn", ref("LandOpOut")),
		"/Farm/CleanEvents":          docOp("Farm 农场", "清别人放在你家的青蛙", "官方走 Farming，item_ids=[5005]，不带地。回 rewards。乌云走 Farm/CleanSocial。", "", ref("CleanFarmEventOut")),
		"/Farm/CanOperate":           docOp("Farm 农场", "预检能不能操作", "operation_id：10001 务农 10004 偷菜 10005 放虫 10006 放草。", "CanOperateIn", ref("CanOperateOut")),
		"/Friend/GetList":            docOp("Friend 好友", "好友列表", "带干旱/杂草/虫害/可偷数量，以及待处理申请数、黑名单、新好友/关注。", "", ref("FriendsOut")),
		"/Friend/Help":               docOp("Friend 好友", "进好友家浇水后离开", "进家带 reason=2。浇完会发 Visit.Leave，避免心跳留在别人家。", "HelpIn", emptyData()),
		"/Friend/Enter":              docOp("Friend 好友", "进好友家", "进别人家带 reason=2。回地块、护主犬、操作次数、天气、在不在家。", "EnterIn", ref("Visit")),
		"/Friend/Leave":              docOp("Friend 好友", "离开好友家", "", "EnterIn", emptyData()),
		"/Friend/Applications":       docOp("Friend 好友", "好友申请", "只看申请，不加好友。", "", ref("ApplicationsOut")),
		"/Friend/Accept":             docOp("Friend 好友", "同意申请", "", "GIDsIn", ref("AcceptOut")),
		"/Friend/Reject":             docOp("Friend 好友", "拒绝申请", "", "GIDsIn", ref("RejectOut")),
		"/Friend/SetTags":            docOp("Friend 好友", "设置好友标签", "协议请求无字段，body 可带但不会发出去。", "TagsIn", ref("Friend")),
		"/Friend/Delete":             docOp("Friend 好友", "删除好友", "", "EnterIn", emptyData()),
		"/Friend/Sync":               docOp("Friend 好友", "同步微信好友", "", "OpenIDsIn", listData("friends", "Friend", "好友")),
		"/Friend/GetGameFriends":     docOp("Friend 好友", "按 gid 批量查", "", "GIDsIn", listData("friends", "Friend", "好友")),
		"/Friend/Block":              docOp("Friend 好友", "拉黑", "", "EnterIn", ref("Blocked")),
		"/Friend/Unblock":            docOp("Friend 好友", "取消拉黑", "", "EnterIn", emptyData()),
		"/Friend/BlockList":          docOp("Friend 好友", "黑名单", "", "", listData("blocked", "Blocked", "黑名单")),
		"/Friend/BlockApplications":  docOp("Friend 好友", "拒收好友申请", "不是拉黑，也不是申请加好友。", "BlockAppsIn", ref("BlockAppsOut")),
		"/Friend/WXRecommend":        docOp("Friend 好友", "微信推荐好友", "encrypted_data 可空。", "WXRecommendIn", ref("WXRecommendOut")),
		"/Friend/WXRecommendPage":    docOp("Friend 好友", "微信推荐分页", "page_size 不填当 20。", "WXRecommendPageIn", ref("WXRecommendOut")),
		"/Friend/ApplyWX":            docOp("Friend 好友", "微信推荐批量加", "body gids。不是申请加好友 ApplyFriend。", "GIDsIn", ref("WXApplyOut")),
		"/Friend/ShareKey":           docOp("Friend 好友", "自己的分享 key", "", "", obj("分享", map[string]any{"share_key": ss("分享串")})),
		"/Share/Check":               docOp("Share 分享", "今日能不能领分享奖", "", "", obj("检查", map[string]any{"can_share": sb("能不能领")})),
		"/Share/Claim":               docOp("Share 分享", "上报分享并领奖", "回 success / has_reward / items。", "", ref("ShareClaimOut")),
		"/Share/InviteInfo":          docOp("Share 分享", "邀请进度", "id 是 share_cfg_id，可不填。", "IDIn", ref("ShareInviteOut")),
		"/Share/InviteAward":         docOp("Share 分享", "领邀请奖", "id 是 share_cfg_id。", "IDIn", ref("ShareAwardOut")),
		"/Share/PosterShown":         docOp("Share 分享", "标记海报已展示", "id 是活动 ID。", "IDIn", obj("结果", map[string]any{"success": sb("是否成功")})),
		"/Share/ReportInvite":        docOp("Share 分享", "上报邀请关系", "点别人分享链后上报。", "InviteReportIn", obj("结果", map[string]any{"success": sb("是否成功")})),
		"/Bag/Get":                   docOp("Bag 背包", "背包", "格子带 uid，后面使用/出售用它。max/used 是格子数。", "", ref("BagOut")),
		"/Bag/Sell":                  docOp("Bag 背包", "出售", "uid 可从 Bag/Get 带上。used 是卖出的，items 是拿到的货币。", "SellIn", ref("ItemOpOut")),
		"/Bag/Use":                   docOp("Bag 背包", "使用", "used 是消耗的那一件，items 是获得。", "UseIn", ref("ItemOpOut")),
		"/Bag/BatchUse":              docOp("Bag 背包", "批量使用", "used 是消耗，items 是获得。", "BatchUseIn", ref("ItemOpOut")),
		"/Bag/Lock":                  docOp("Bag 背包", "锁格子", "", "UIDsIn", ref("LockOut")),
		"/Bag/Unlock":                docOp("Bag 背包", "解锁格子", "", "UIDsIn", ref("LockOut")),
		"/Bag/CancelNew":             docOp("Bag 背包", "清新标记", "协议方法名是 CannelNew。", "IDIn", obj("结果", map[string]any{"id": si("物品 ID")})),
		"/Shop/List":                 docOp("Shop 商店", "商店列表", "", "", listData("shops", "Shop", "商店")),
		"/Shop/Goods":                docOp("Shop 商店", "商品", "不填 shop_id 则种子店 2。", "ShopIn", listData("goods", "Goods", "货架")),
		"/Shop/Buy":                  docOp("Shop 商店", "购买", "price 用货架上的单价。", "BuyIn", ref("BuyOut")),
		"/Shop/AutoBuy":              docOp("Shop 商店", "按物品查货架再买", "不填 shop_id 则种子店。超限购会拒绝或截到剩余次数。", "AutoBuyIn", ref("BuyOut")),
		"/Weather/Status":            docOp("Weather 天气", "农场实时天气状态", "can_collect=true 才能做雨落成诗采集。", "", ref("Weather")),
		"/Weather/Current":           docOp("Weather 天气", "此刻天气", "GetCurrentWeather，带名字和起止时间。", "", ref("Weather")),
		"/Weather/Today":             docOp("Weather 天气", "今日天气", "", "", listData("weathers", "Weather", "天气")),
		"/Task/List":                 docOp("Task 任务", "成长/每日任务和活跃度宝箱", "", "", ref("TaskBoard")),
		"/Task/Claim":                docOp("Task 任务", "领任务", "一个用 id，多个用 ids。回 items / compensated。", "ClaimIn", ref("TaskClaimOut")),
		"/Task/ClaimDaily":           docOp("Task 任务", "领活跃度宝箱", "只发 point_ids。", "DailyIn", ref("TaskClaimOut")),
		"/Task/Report":               docOp("Task 任务", "上报任务进度", "回包是更新后的任务总览。", "TaskReportIn", ref("TaskBoard")),
		"/Email/List":                docOp("Email 邮件", "邮件列表", "box 不填为 1。列表 read 是已读，不是已领。已领看详情。", "EmailBoxIn", listData("emails", "Email", "邮件")),
		"/Email/Read":                docOp("Email 邮件", "读邮件", "id 是字符串。", "EmailIn", ref("EmailDetail")),
		"/Email/Claim":               docOp("Email 邮件", "领一封", "", "EmailIn", itemsData()),
		"/Email/ClaimAll":            docOp("Email 邮件", "批量领", "不填 box 则 1 和 2 都领。没领成的在 unclaimed。", "EmailBoxIn", ref("EmailClaimOut")),
		"/Email/BatchRead":           docOp("Email 邮件", "批量已读", "", "EmailIDsIn", emptyData()),
		"/Email/BatchDelete":         docOp("Email 邮件", "批量删除", "", "EmailIDsIn", emptyData()),
		"/Activity/List":             docOp("Activity 清单", "活动清单", "每条有 start/end（Unix 秒）和 status（1 进行中，2 已结束）。活动号不是开日。礼包核实：雨落成诗 2026070301 2026-08-26 10:00 ~ 2026-09-08 23:59；鹊桥 2026081801/2026081802 2026-08-18 10:00 ~ 2026-08-22 23:59；千星 2026072701 2026-07-29 10:00 ~ 2026-08-27 23:59。其余仅活动号，开停以该条 start/end 为准。", "", listData("activities", "Activity", "活动")),
		"/Activity/GetGroup":         docOp("Activity 清单", "活动组详情", "id 或 group_id 都行。List 里没有每日限购货架或建设节点时打这个。窗口看组的 start/end。", "GroupIn", ref("ActivityGroup")),
		"/Activity/SetSplashed":      docOp("Activity 清单", "标记活动开屏已看", "窗口看该条 start/end。", "IDIn", obj("结果", map[string]any{"success": sb("是否成功")})),
		"/Activity/Invitees":         docOp("Activity 邀新领红包", "邀新领红包被邀请名单", "活动号 2026080701，仅活动号，开停看带 invite 那条的 start/end。", "IDIn", listData("invitees", "Invitee", "被邀请的人")),
		"/Activity/Signin":           docOp("Activity 青酿换万金", "活动签到", "reward_id 可不填，从列表取。青酿日签 2026080102，仅活动号，开停看该条 start/end。", "ActivityOpIn", ref("ActivityOpOut")),
		"/Activity/ClaimProgress":    docOp("Activity 鹊桥寄情", "领进度奖", "step 一般 0。鹊桥寄情筑桥 2026081801。礼包 2026-08-18 10:00 ~ 2026-08-22 23:59，精确看带 progress 那条的 start/end。", "ActivityOpIn", ref("ActivityOpOut")),
		"/Activity/ShopBuy":          docOp("Activity 雨落成诗", "活动商店买一件", "雨落成诗每日限购：金豆豆 1005 买采集瓶 5001。自己指定，不自动买。活动号 2026070301。礼包 2026-08-26 10:00 ~ 2026-09-08 23:59，精确看带 shop 那条的 start/end。", "ActivityShopIn", ref("ActivityOpOut")),
		"/Activity/ShopBatchBuy":     docOp("Activity 雨落成诗", "活动商店批量买", "自己指定，不自动买。开停看带 shop 那条的 start/end。", "ActivityBatchIn", ref("ActivityOpOut")),
		"/Activity/RandBuy":          docOp("Activity 抽奖签到店", "随机商店买一件", "货架在 Activity/List 的 rand_shop。开停看该条 start/end。", "ActivityShopIn", ref("ActivityOpOut")),
		"/Activity/RandRefresh":      docOp("Activity 抽奖签到店", "刷新随机商店", "costs 是这次扣掉的，新货在 activity.rand_shop。开停看该条 start/end。", "IDIn", ref("ActivityOpOut")),
		"/Activity/ClaimMega":        docOp("Activity 观星礼录", "观星礼录一键领", "days 是刚领的天数。千星游记 2026072701。礼包 2026-07-29 10:00 ~ 2026-08-27 23:59，精确看带 mega 那条的 start/end。", "ActivityOpIn", ref("ActivityOpOut")),
		"/Activity/TechSubmit":       docOp("Activity 雨落成诗", "雨落成诗建设/领取", "提交 nodes 里 status 为 2 或 3 的节点，领采集瓶等。回 items / unlocked / activity。活动号 2026070301。礼包 2026-08-26 10:00 ~ 2026-09-08 23:59，精确看带 nodes 那条的 start/end。", "TechIn", ref("ActivityOpOut")),
		"/Activity/Draw":             docOp("Activity 抽奖签到店", "活动抽奖", "列表 draw 子结构。count 不填当 1。开停看该条 start/end。", "DrawIn", ref("ActivityOpOut")),
		"/Activity/DrawHistory":      docOp("Activity 抽奖签到店", "活动抽奖历史", "开停看该条 start/end。", "IDIn", ref("DrawHistoryOut")),
		"/Activity/MarkViewed":       docOp("Activity 清单", "标记活动已看", "只发活动 ID。开停看该条 start/end。", "IDIn", ref("ActivityOpOut")),
		"/Activity/RandBatchBuy":     docOp("Activity 抽奖签到店", "随机商店批量买", "货架在 Activity/List 的 rand_shop。开停看该条 start/end。", "ActivityBatchIn", ref("ActivityOpOut")),
		"/Activity/LotteryHistory":   docOp("Activity 雨落成诗", "雨落成诗采集历史", "活动号 2026070301。礼包 2026-08-26 10:00 ~ 2026-09-08 23:59，精确看带 lottery 那条的 start/end。", "IDIn", ref("LotteryHistoryOut")),
		"/Activity/CheerJoin":        docOp("Activity 阵营加油", "加入加油阵营", "粽香 2026061901，足球 2026071501。仅活动号，开停看带 cheer 那条的 start/end。", "CheerJoinIn", ref("ActivityOpOut")),
		"/Activity/CheerSubmit":      docOp("Activity 阵营加油", "提交加油", "档期同 CheerJoin。", "CheerSubmitIn", ref("CheerSubmitOut")),
		"/Activity/CheerClaim":       docOp("Activity 阵营加油", "领加油档奖励", "档期同 CheerJoin。", "CheerClaimIn", ref("ActivityOpOut")),
		"/Activity/Recallable":       docOp("Activity 故友重逢", "可召回名单", "故友重逢。活动号 2026070101，仅活动号，开停看带 recall 那条的 start/end。", "IDIn", ref("RecallListOut")),
		"/Activity/Recalled":         docOp("Activity 故友重逢", "已召回名单", "故友重逢。活动号 2026070101，仅活动号，开停看带 recall 那条的 start/end。", "IDIn", ref("RecallListOut")),
		"/Activity/CharityShare":     docOp("Activity 公益小红花", "公益花领分享奖", "活动号 2026090901，仅活动号，开停看带 charity 那条的 start/end。", "IDIn", ref("ActivityOpOut")),
		"/Activity/CharityDonate":    docOp("Activity 公益小红花", "公益花捐出全部爱心", "档期同 CharityShare。", "IDIn", ref("CharityDonateOut")),
		"/Activity/CharityClaim":     docOp("Activity 公益小红花", "公益花领个人档", "score 是档位所需个人积分。档期同 CharityShare。", "CharityClaimIn", ref("ActivityOpOut")),
		"/Activity/CharityXhh":       docOp("Activity 公益小红花", "公益花领星辉回", "档期同 CharityShare。", "IDIn", ref("CharityXhhOut")),
		"/Activity/CharityAgree":     docOp("Activity 公益小红花", "公益花合规同意", "档期同 CharityShare。", "CharityAgreeIn", ref("ActivityOpOut")),
		"/Activity/HuntFinishCG":     docOp("Activity 宠物寻宝", "宠物寻宝结束 CG", "cmd 901。活动号 2026090101，仅活动号，开停看带 hunt 那条的 start/end。", "IDIn", ref("ActivityOpOut")),
		"/Activity/HuntGuide":        docOp("Activity 宠物寻宝", "宠物寻宝引导", "cmd 902。档期同 HuntFinishCG。", "IDIn", ref("ActivityOpOut")),
		"/Activity/HuntFeed":         docOp("Activity 宠物寻宝", "宠物寻宝喂养", "cmd 903。档期同 HuntFinishCG。", "IDIn", ref("ActivityOpOut")),
		"/Activity/HuntDraw":         docOp("Activity 宠物寻宝", "宠物寻宝抽奖", "cmd 904。不是 Activity/Draw。档期同 HuntFinishCG。", "IDIn", ref("ActivityOpOut")),
		"/Activity/HuntLog":          docOp("Activity 宠物寻宝", "宠物寻宝日志", "cmd 905。档期同 HuntFinishCG。", "IDIn", ref("HuntLogOut")),
		"/Activity/HuntClaimStory":   docOp("Activity 宠物寻宝", "宠物寻宝领剧情", "cmd 906。档期同 HuntFinishCG。", "IDIn", ref("ActivityOpOut")),
		"/Activity/HuntClaimSeed":    docOp("Activity 宠物寻宝", "宠物寻宝领种子", "cmd 907。档期同 HuntFinishCG。", "IDIn", ref("ActivityOpOut")),
		"/Activity/HuntRefreshCharm": docOp("Activity 宠物寻宝", "宠物寻宝刷新护符池", "cmd 908。消耗看配置，点券 1002。档期同 HuntFinishCG。", "IDIn", ref("ActivityOpOut")),
		"/Activity/HuntEquip":        docOp("Activity 宠物寻宝", "宠物寻宝装备护符", "cmd 909。body charm_ids。护符 101–105。档期同 HuntFinishCG。", "HuntEquipIn", ref("ActivityOpOut")),
		"/Activity/HuntBattle":       docOp("Activity 宠物寻宝", "宠物寻宝开战/掠夺", "cmd 910。defender_gid 和 treasure_id 必填。档期同 HuntFinishCG。", "HuntBattleIn", ref("ActivityOpOut")),
		"/Activity/HuntPlunderedLog": docOp("Activity 宠物寻宝", "宠物寻宝被掠日志", "cmd 911。档期同 HuntFinishCG。", "IDIn", ref("HuntLogOut")),
		"/Activity/HuntOpen":         docOp("Activity 宠物寻宝", "宠物寻宝开宝", "cmd 913。有可领宝藏时游戏会打这个。档期同 HuntFinishCG。", "IDIn", ref("ActivityOpOut")),
		"/Activity/HuntEscort":       docOp("Activity 宠物寻宝", "宠物寻宝护送", "cmd 914。档期同 HuntFinishCG。", "IDIn", ref("ActivityOpOut")),
		"/Activity/HuntCompensate":   docOp("Activity 宠物寻宝", "宠物寻宝领掠夺补偿", "cmd 915。档期同 HuntFinishCG。", "IDIn", ref("ActivityOpOut")),
		"/Activity/HuntFriendInfo":   docOp("Activity 宠物寻宝", "宠物寻宝查好友活动", "cmd 916。档期同 HuntFinishCG。", "IDIn", ref("ActivityOpOut")),
		"/Activity/Lottery":          docOp("Activity 雨落成诗", "雨落成诗采集", "消耗天气采集瓶 5001。host_gid 必须 can_collect。自己指定，不自动巡访。活动号 2026070301。礼包 2026-08-26 10:00 ~ 2026-09-08 23:59，精确看带 lottery 那条的 start/end。", "LotteryIn", ref("LotteryOut")),
		"/Activity/BrewStart":        docOp("Activity 青酿换万金", "开始酿酒", "uid 是背包槽位。青酿换万金 2026080102 / 2026081202，仅活动号，开停看带 brew 那条的 start/end。", "BrewStartIn", ref("BrewStartOut")),
		"/Activity/BrewStep":         docOp("Activity 青酿换万金", "酿酒下一步", "档期同 BrewStart。", "ActivityOpIn", ref("BrewStepOut")),
		"/Activity/BrewClaim":        docOp("Activity 青酿换万金", "领酿酒", "claim_type：1 普通 2 分享。档期同 BrewStart。", "BrewClaimIn", ref("ActivityOpOut")),
		"/Activity/ClaimRecall":      docOp("Activity 故友重逢", "故友重逢召回奖", "活动号 2026070101，仅活动号，开停看带 recall 那条的 start/end。", "ActivityOpIn", ref("ActivityOpOut")),
		"/Activity/ClaimReturn":      docOp("Activity 故友重逢", "故友重逢回归礼", "活动号 2026070101，仅活动号，开停看带 recall 那条的 start/end。", "ActivityOpIn", ref("ActivityOpOut")),
		"/Activity/ClaimInvite":      docOp("Activity 邀新领红包", "邀新领红包邀请/成长档", "reward_type：1 邀请 2 成长。活动号 2026080701，仅活动号，开停看带 invite 那条的 start/end。", "InviteIn", ref("ActivityOpOut")),
		"/Activity/ClaimNewcomer":    docOp("Activity 邀新领红包", "邀新领红包新人档", "活动号 2026080701，仅活动号，开停看带 invite 那条的 start/end。", "ActivityOpIn", ref("ActivityOpOut")),
		"/Activity/SendGift":         docOp("Activity 鹊桥寄情", "给指定好友送礼", "不群发。鹊桥寄情香囊 2026081802。礼包 2026-08-18 10:00 ~ 2026-08-22 23:59，精确看带 gift 那条的 start/end。", "GiftIn", obj("送礼", map[string]any{"total_send_count": si("已送次数")})),
		"/Mystery/Status":            docOp("Mystery 神秘商人", "是否在、货架", "", "", ref("MysteryShop")),
		"/Mystery/Buy":               docOp("Mystery 神秘商人", "买一件", "id 是卡片 ID。goods 是更新后的货架。", "IDIn", ref("MysteryBuyOut")),
		"/Mystery/AutoBuy":           docOp("Mystery 神秘商人", "买当前未购商品", "可按 currency 过滤。买到一半失败会继续，失败项在 failed。", "MysteryAutoIn", ref("MysteryAutoOut")),
		"/Mystery/Leave":             docOp("Mystery 神秘商人", "打发商人", "", "", emptyData()),
		"/Season/Info":               docOp("Season 赛季", "赛季和通行证", "带回预热、活动简介、战令各档。千星游记赛季号 2026072700。礼包 2026-07-29 10:00 ~ 2026-08-27 23:59，精确看 Season.start / Season.end。", "", ref("Season")),
		"/Season/ClaimPass":          docOp("Season 赛季", "领已解锁的战令奖励", "带回刚领的等级和更新后的战令。", "", ref("PassClaimOut")),
		"/Season/BuyPass":            docOp("Season 赛季", "买高级战令", "空请求。回 success / items / pass。", "", ref("BuyPassOut")),
		"/Season/MarkOpening":        docOp("Season 赛季", "标记开幕已看", "", "", obj("结果", map[string]any{"success": sb("是否成功")})),
		"/Mall/Profiles":             docOp("Mall 商城", "商城档位", "", "", listData("profiles", "MallProfile", "档位")),
		"/Mall/Diamonds":             docOp("Mall 商城", "点券货架", "", "", listData("products", "Product", "商品")),
		"/Mall/List":                 docOp("Mall 商城", "商城商品", "slot 不填为 1。", "MallIn", listData("products", "Product", "商品")),
		"/Mall/Buy":                  docOp("Mall 商城", "买/领商城商品", "自己指定，不自动买。f2 是 success，奖励在 items。", "MallBuyIn", ref("BuyOut")),
		"/Mall/MonthCard":            docOp("Mall 商城", "月卡", "", "", listData("cards", "MonthCard", "月卡")),
		"/Mall/ClaimMonthCard":       docOp("Mall 商城", "领月卡", "带回更新后的月卡。", "IDIn", ref("MonthCardClaimOut")),
		"/RedPacket/List":            docOp("RedPacket 红包", "今日红包", "can_claim 是今日未领且 status 非 0。", "", listData("packets", "RedPacket", "红包")),
		"/RedPacket/Claim":           docOp("RedPacket 红包", "领一个", "回 status 和这一件奖励。", "IDIn", ref("RedPacketClaimOut")),
		"/RedPacket/ClaimAll":        docOp("RedPacket 红包", "领完能领的", "", "", itemsData()),
		"/Visit/Logs":                docOp("Visit 来访", "来访记录", "action：1浇水 2除虫 3除草 4偷菜 5放虫 6放草。", "", listData("logs", "VisitLog", "记录")),
		"/Visit/Summary":             docOp("Visit 来访", "来往摘要", "总偷菜/帮忙/捣乱和按好友明细。网关若没有这个方法会 502。", "", ref("VisitSummary")),
		"/Visit/Popup":               docOp("Visit 来访", "来访弹窗", "未读 / 要不要弹。", "", ref("VisitPopup")),
		"/Visit/Page":                docOp("Visit 来访", "分页来访", "page 不填为 1。", "VisitPageIn", listData("logs", "VisitLog", "记录")),
		"/Visit/Dismiss":             docOp("Visit 来访", "关掉弹窗", "", "EnterIn", emptyData()),
		"/Visit/Delete":              docOp("Visit 来访", "删记录", "", "VisitDeleteIn", emptyData()),
		"/Album/List":                docOp("Album 图鉴", "图鉴", "type 不填为普通 1，2 是超变。", "AlbumIn", ref("Album")),
		"/Album/Levels":              docOp("Album 图鉴", "图鉴等级列表", "type 不填为 1。", "AlbumIn", ref("AlbumLevels")),
		"/Album/Claim":               docOp("Album 图鉴", "领图鉴奖励", "带回刚领的等级和下一级预览。", "AlbumIn", ref("AlbumClaimOut")),
		"/Album/MarkViewed":          docOp("Album 图鉴", "清图鉴新解锁标记", "type 不填为 1。", "AlbumIn", emptyData()),
		"/Dog/Info":                  docOp("Dog 护主犬", "狗、狗粮、待领礼物", "", "", ref("DogYard")),
		"/Dog/Feed":                  docOp("Dog 护主犬", "喂狗粮", "food_id 从 Dog/Info 取。不自动补。", "FeedIn", obj("喂完", map[string]any{"food_left": si("剩余秒")})),
		"/Dog/ClaimGifts":            docOp("Dog 护主犬", "领技能礼物", "compensated 是背包满补偿。", "", ref("DogGiftOut")),
		"/Dog/Logs":                  docOp("Dog 护主犬", "护院日志", "count 不填为 50。", "PageIn", ref("DogLogsOut")),
		"/Dog/Deploy":                docOp("Dog 护主犬", "出战", "", "IDIn", ref("DeployOut")),
		"/Dog/Withdraw":              docOp("Dog 护主犬", "收回出战犬", "", "", ref("DeployOut")),
		"/Dog/Activate":              docOp("Dog 护主犬", "激活已有的狗", "", "IDIn", ref("Dog")),
		"/Dog/Buy":                   docOp("Dog 护主犬", "买并激活", "price 不填从 Dog/Info 取。", "DogBuyIn", ref("DogBuyOut")),
		"/Bulletin/List":             docOp("Bulletin 公告", "公告列表", "count 不填为 20。", "PageIn", listData("bulletins", "Bulletin", "公告")),
		"/Bulletin/Read":             docOp("Bulletin 公告", "公告正文", "", "IDIn", ref("BulletinDetail")),
		"/Mutant/List":               docOp("Mutant 变异", "变异宝典", "条目是活动窗口，不是果实图鉴。开停看每条自己的窗口。", "", listData("mutants", "Mutant", "条目")),
		"/Mutant/OpenInfo":           docOp("Mutant 变异", "变异系统开放奖励", "走 Mutant.GetSystemOpenInfo，不是 SystemOpen 解锁查询。", "", ref("MutantOpenInfoOut")),
		"/QQVip/DailyStatus":         docOp("QQVip 会员", "每日礼状态", "是不是会员、今天能不能领、奖励预览。", "", ref("QQVipDailyOut")),
		"/QQVip/ClaimDaily":          docOp("QQVip 会员", "领每日礼", "config_id 可空，有当前档就带上。", "QQVipClaimDailyIn", ref("QQVipClaimDailyOut")),
		"/QQVip/Refresh":             docOp("QQVip 会员", "刷新会员信息", "空请求。回 is_qq_vip / vip_level。", "", ref("QQVipRefreshOut")),
		"/QQVip/ClaimRewards":        docOp("QQVip 会员", "领会员奖励", "config_ids 来自 RewardsStatus.active_configs。", "QQVipClaimRewardsIn", ref("QQVipClaimRewardsOut")),
		"/QQVip/RewardsStatus":       docOp("QQVip 会员", "会员奖励状态", "当前档、红点、能不能领。", "", ref("QQVipRewardsStatusOut")),
		"/QQVip/MarkRedpoint":        docOp("QQVip 会员", "清会员红点", "空请求空回包。", "", emptyData()),
		"/Marquee/List":              docOp("Marquee 跑马灯", "跑马灯列表", "空请求。", "", ref("MarqueeOut")),
		"/SystemOpen/Unlocked":       docOp("SystemOpen 系统解锁", "查系统是否已开", "system_name 是官方枚举编号。", "SystemOpenIn", ref("SystemOpenOut")),
		"/Subscribe/QQ":              docOp("Subscribe 订阅", "QQ 订阅状态", "空请求。回包可能是标量 status，也可能是 items 列表。", "", ref("QQSubscribeOut")),
		"/Subscribe/WX":              docOp("Subscribe 订阅", "微信订阅状态", "空请求。", "", ref("WXSubscribeOut")),
		"/Subscribe/SetWX":           docOp("Subscribe 订阅", "写微信订阅", "templates 必填。", "WXSubscribeIn", ref("WXSubscribeOut")),
		"/Moderate/Text":             docOp("Moderate 审核", "审一条文本", "text 必填。", "ModerateTextIn", ref("ModerateTextOut")),
		"/Moderate/BatchText":        docOp("Moderate 审核", "批量审文本", "text_items 必填。", "ModerateTextBatchIn", ref("ModerateTextBatchOut")),
		"/Moderate/Pic":              docOp("Moderate 审核", "审一张图", "pic_url 必填。", "ModeratePicIn", ref("ModeratePicOut")),
		"/Moderate/BatchPic":         docOp("Moderate 审核", "批量审图", "pic_items 必填。", "ModeratePicBatchIn", ref("ModeratePicBatchOut")),
		"/Career/Info":               docOp("Career 生涯", "生涯收获/被偷", "请求无字段，只查当前登录号。", "", ref("Career")),
		"/Rank/List":                 docOp("Rank 排行", "排行榜", "type：1等级 2金币 3图鉴。都不填则 type=1、page=1。", "RankIn", ref("RankBoard")),
		"/Avatar/Owned":              docOp("Avatar 头像框", "已有头像框", "type 可筛选。", "TypeIn", listData("avatars", "Avatar", "头像框")),
		"/Avatar/Equipped":           docOp("Avatar 头像框", "当前头像框", "", "", listData("avatars", "Avatar", "头像框")),
		"/Avatar/Equip":              docOp("Avatar 头像框", "穿或脱", "off=true 卸下。", "AvatarEquipIn", ref("Avatar")),
		"/Avatar/MarkViewed":         docOp("Avatar 头像框", "标记已查看", "", "IDIn", emptyData()),
		"/Skin/Owned":                docOp("Skin 皮肤", "已有皮肤", "", "", listData("skins", "Skin", "皮肤")),
		"/Skin/Equipped":             docOp("Skin 皮肤", "当前皮肤", "", "", listData("skins", "Skin", "皮肤")),
		"/Skin/Equip":                docOp("Skin 皮肤", "换皮肤", "id=0 卸下。", "SkinEquipIn", emptyData()),
		"/Skin/EquipSet":             docOp("Skin 皮肤", "穿套装", "skin_ids 必填。", "SkinSetIn", emptyData()),
		"/Skin/SetEffect":            docOp("Skin 皮肤", "开关套装特效", "set_id 必填。", "SkinSetEffectIn", emptyData()),
		"/Skin/Sets":                 docOp("Skin 皮肤", "当前套装特效", "从已装备皮肤 field 2 读。", "", listData("sets", "SkinSetEffect", "套装特效")),
		"/Skin/MarkViewed":           docOp("Skin 皮肤", "标记已查看", "", "IDIn", emptyData()),
		"/QQGroup/AuthGroups":        docOp("QQGroup 群", "已授权 QQ 群", "cookies 可空。", "CookiesIn", ref("QQAuthGroupsOut")),
		"/QQGroup/Recommend":         docOp("QQGroup 群", "推荐群", "", "QQRecommendIn", ref("QQRecommendOut")),
		"/QQGroup/Bind":              docOp("QQGroup 群", "绑定社群", "community_id 必填。", "QQBindIn", ref("QQBindOut")),
		"/QQGroup/Leave":             docOp("QQGroup 群", "退出社群", "", "", ref("QQLeaveOut")),
		"/QQGroup/Community":         docOp("QQGroup 群", "社群信息", "from 当页码，不填当 1。", "PageIn", ref("QQCommunityOut")),
		"/QQGroup/BindInfo":          docOp("QQGroup 群", "绑定详情", "", "", ref("QQBindInfoOut")),
		"/QQGroup/ClaimReward":       docOp("QQGroup 群", "领社群绑定奖", "", "", itemsData()),
		"/QQGroup/RevokeAuth":        docOp("QQGroup 群", "撤销授权", "community_id 必填。", "QQRevokeIn", emptyData()),
		"/Gift/UseToken":             docOp("Gift 礼包", "使用礼包码道具", "uid 是背包格子，不是兑换码。兑换码在回包 redeem_code。", "UIDIn", ref("GiftTokenOut")),
		"/Gift/History":              docOp("Gift 礼包", "礼包领取历史", "page 不填当 1，page_size 不填当 20。", "GiftHistoryIn", ref("GiftHistoryOut")),
		"/Gift/TransferStatus":       docOp("Gift 礼包", "查转账状态", "out_bill_no 必填。", "TransferIn", ref("TransferOut")),
		"/Gift/CancelTransfer":       docOp("Gift 礼包", "取消红包转账", "uid 是背包格子。", "UIDIn", ref("TransferOut")),
		"/Follow/Status":             docOp("Follow 关注有礼", "关注有礼状态", "游戏里夹在杂项。", "", ref("FollowGiftOut")),
		"/Follow/Set":                docOp("Follow 关注有礼", "标记已关注", "", "FollowGiftIn", emptyData()),
		"/Follow/Claim":              docOp("Follow 关注有礼", "领关注礼", "", "", itemsData()),
		"/Recharge/Config":           docOp("Recharge 充值返利", "返利配置", "", "", ref("RechargeBonusOut")),
		"/Recharge/Data":             docOp("Recharge 充值返利", "返利进度", "", "", ref("RechargeDataOut")),
		"/Drop/List":                 docOp("Drop 掉落", "随机掉落活动", "只读。开停看每条自己的窗口，或 Activity/List 的 drops。", "", listData("drops", "Drop", "活动")),
		"/Solar/List":                docOp("Solar 节气", "节气列表", "status：1未到 2可领 3已领 4过期未领 5过期已领。带回服务端时间和赛季配置。", "", ref("SolarOut")),
		"/Solar/Claim":               docOp("Solar 节气", "领一个节气", "event 是更新后的节气。", "IDIn", ref("SolarClaimOut")),
		"/Solar/ClaimAll":            docOp("Solar 节气", "领完当前可领的", "", "", itemsData()),
		"/Solar/RedDot":              docOp("Solar 节气", "节气红点", "", "", ref("RedDot")),
		"/Achieve/View":              docOp("Achieve 成就", "成就域", "", "AchieveIn", ref("AchieveScope")),
		"/Achieve/ClaimGoal":         docOp("Achieve 成就", "领成就目标", "f1 是域经验，不是物品。", "AchieveGoalIn", ref("AchieveGoalOut")),
		"/Achieve/ClaimLevel":        docOp("Achieve 成就", "领成就域等级", "items 是奖励，compensated 是补偿。", "AchieveIn", ref("ItemOpOut")),
	}
}
